//
// CallingSettingsCallingSip.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** SIP trunk settings. When SIP is ENABLED, Graph call actions and calling webhooks are not used — Meta dials your SIP server directly.  */
public struct CallingSettingsCallingSip: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case enabled = "ENABLED"
        case disabled = "DISABLED"
    }
    public var status: Status?
    public var servers: [CallingSettingsCallingSipServersInner]?

    public init(status: Status? = nil, servers: [CallingSettingsCallingSipServersInner]? = nil) {
        self.status = status
        self.servers = servers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case servers
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(servers, forKey: .servers)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        status = try container.decodeIfPresent(Status.self, forKey: .status)
        servers = try container.decodeIfPresent([CallingSettingsCallingSipServersInner].self, forKey: .servers)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("status")
        nonAdditionalPropertyKeys.insert("servers")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

