//
// CallingSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Calling settings payload for GET/POST &#x60;/callingSettings&#x60;. Proxies upstream &#x60;GET|POST /calling/settings&#x60;. Extra Meta fields may appear on GET responses; document core fields below.  */
public struct CallingSettings: Codable, JSONEncodable, Hashable {

    public var calling: CallingSettingsCalling?

    public init(calling: CallingSettingsCalling? = nil) {
        self.calling = calling
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case calling
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(calling, forKey: .calling)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        calling = try container.decodeIfPresent(CallingSettingsCalling.self, forKey: .calling)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("calling")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

