//
// CallingSettingsCallingSipServersInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CallingSettingsCallingSipServersInner: Codable, JSONEncodable, Hashable {

    public var hostname: String?
    public var port: Int?
    public var requestUriUserParams: [String: String]?
    /** Present on GET when SIP credentials are returned by Meta */
    public var sipUserPassword: String?
    /** Alternate password field name from some Meta responses */
    public var password: String?
    public var appId: String?

    public init(hostname: String? = nil, port: Int? = nil, requestUriUserParams: [String: String]? = nil, sipUserPassword: String? = nil, password: String? = nil, appId: String? = nil) {
        self.hostname = hostname
        self.port = port
        self.requestUriUserParams = requestUriUserParams
        self.sipUserPassword = sipUserPassword
        self.password = password
        self.appId = appId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hostname
        case port
        case requestUriUserParams = "request_uri_user_params"
        case sipUserPassword = "sip_user_password"
        case password
        case appId = "app_id"
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(hostname, forKey: .hostname)
        try container.encodeIfPresent(port, forKey: .port)
        try container.encodeIfPresent(requestUriUserParams, forKey: .requestUriUserParams)
        try container.encodeIfPresent(sipUserPassword, forKey: .sipUserPassword)
        try container.encodeIfPresent(password, forKey: .password)
        try container.encodeIfPresent(appId, forKey: .appId)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        hostname = try container.decodeIfPresent(String.self, forKey: .hostname)
        port = try container.decodeIfPresent(Int.self, forKey: .port)
        requestUriUserParams = try container.decodeIfPresent([String: String].self, forKey: .requestUriUserParams)
        sipUserPassword = try container.decodeIfPresent(String.self, forKey: .sipUserPassword)
        password = try container.decodeIfPresent(String.self, forKey: .password)
        appId = try container.decodeIfPresent(String.self, forKey: .appId)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("hostname")
        nonAdditionalPropertyKeys.insert("port")
        nonAdditionalPropertyKeys.insert("request_uri_user_params")
        nonAdditionalPropertyKeys.insert("sip_user_password")
        nonAdditionalPropertyKeys.insert("password")
        nonAdditionalPropertyKeys.insert("app_id")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

