//
// CallingSettingsCallingCallHours.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Optional call hours / timezone configuration (Meta shape) */
public struct CallingSettingsCallingCallHours: Codable, JSONEncodable, Hashable {

    public var status: String?
    public var timezone: String?
    public var dayOfWeekStart: String?

    public init(status: String? = nil, timezone: String? = nil, dayOfWeekStart: String? = nil) {
        self.status = status
        self.timezone = timezone
        self.dayOfWeekStart = dayOfWeekStart
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case timezone
        case dayOfWeekStart = "day_of_week_start"
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(timezone, forKey: .timezone)
        try container.encodeIfPresent(dayOfWeekStart, forKey: .dayOfWeekStart)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        status = try container.decodeIfPresent(String.self, forKey: .status)
        timezone = try container.decodeIfPresent(String.self, forKey: .timezone)
        dayOfWeekStart = try container.decodeIfPresent(String.self, forKey: .dayOfWeekStart)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("status")
        nonAdditionalPropertyKeys.insert("timezone")
        nonAdditionalPropertyKeys.insert("day_of_week_start")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

