//
// CallingSettingsCalling.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Calling feature configuration for the business phone number */
public struct CallingSettingsCalling: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case enabled = "ENABLED"
        case disabled = "DISABLED"
    }
    public enum CallIconVisibility: String, Codable, CaseIterable {
        case _default = "DEFAULT"
        case disableAll = "DISABLE_ALL"
    }
    public enum CallbackPermissionStatus: String, Codable, CaseIterable {
        case enabled = "ENABLED"
        case disabled = "DISABLED"
    }
    public enum SrtpKeyExchangeProtocol: String, Codable, CaseIterable {
        case dtls = "DTLS"
        case sdes = "SDES"
    }
    /** Enable or disable Calling API on this number */
    public var status: Status?
    /** Controls call icon visibility in the WhatsApp client */
    public var callIconVisibility: CallIconVisibility?
    /** When ENABLED, a user who calls your business automatically grants call permission for business-initiated callbacks (subject to Meta rules).  */
    public var callbackPermissionStatus: CallbackPermissionStatus?
    /** SRTP key exchange. DTLS is default/recommended. SDES is only valid when SIP signaling is enabled.  */
    public var srtpKeyExchangeProtocol: SrtpKeyExchangeProtocol?
    public var callHours: CallingSettingsCallingCallHours?
    public var sip: CallingSettingsCallingSip?
    public var video: CallingSettingsCallingVideo?
    public var audio: CallingSettingsCallingAudio?
    /** Calling restrictions (response-only) */
    public var restrictions: [String: AnyCodable]?
    /** Meta media IP ranges (response-only) */
    public var ipAddresses: [String: AnyCodable]?
    /** Call icon country restrictions (response-only) */
    public var callIcons: [String: AnyCodable]?

    public init(status: Status? = nil, callIconVisibility: CallIconVisibility? = nil, callbackPermissionStatus: CallbackPermissionStatus? = nil, srtpKeyExchangeProtocol: SrtpKeyExchangeProtocol? = nil, callHours: CallingSettingsCallingCallHours? = nil, sip: CallingSettingsCallingSip? = nil, video: CallingSettingsCallingVideo? = nil, audio: CallingSettingsCallingAudio? = nil, restrictions: [String: AnyCodable]? = nil, ipAddresses: [String: AnyCodable]? = nil, callIcons: [String: AnyCodable]? = nil) {
        self.status = status
        self.callIconVisibility = callIconVisibility
        self.callbackPermissionStatus = callbackPermissionStatus
        self.srtpKeyExchangeProtocol = srtpKeyExchangeProtocol
        self.callHours = callHours
        self.sip = sip
        self.video = video
        self.audio = audio
        self.restrictions = restrictions
        self.ipAddresses = ipAddresses
        self.callIcons = callIcons
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case callIconVisibility = "call_icon_visibility"
        case callbackPermissionStatus = "callback_permission_status"
        case srtpKeyExchangeProtocol = "srtp_key_exchange_protocol"
        case callHours = "call_hours"
        case sip
        case video
        case audio
        case restrictions
        case ipAddresses = "ip_addresses"
        case callIcons = "call_icons"
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(callIconVisibility, forKey: .callIconVisibility)
        try container.encodeIfPresent(callbackPermissionStatus, forKey: .callbackPermissionStatus)
        try container.encodeIfPresent(srtpKeyExchangeProtocol, forKey: .srtpKeyExchangeProtocol)
        try container.encodeIfPresent(callHours, forKey: .callHours)
        try container.encodeIfPresent(sip, forKey: .sip)
        try container.encodeIfPresent(video, forKey: .video)
        try container.encodeIfPresent(audio, forKey: .audio)
        try container.encodeIfPresent(restrictions, forKey: .restrictions)
        try container.encodeIfPresent(ipAddresses, forKey: .ipAddresses)
        try container.encodeIfPresent(callIcons, forKey: .callIcons)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        status = try container.decodeIfPresent(Status.self, forKey: .status)
        callIconVisibility = try container.decodeIfPresent(CallIconVisibility.self, forKey: .callIconVisibility)
        callbackPermissionStatus = try container.decodeIfPresent(CallbackPermissionStatus.self, forKey: .callbackPermissionStatus)
        srtpKeyExchangeProtocol = try container.decodeIfPresent(SrtpKeyExchangeProtocol.self, forKey: .srtpKeyExchangeProtocol)
        callHours = try container.decodeIfPresent(CallingSettingsCallingCallHours.self, forKey: .callHours)
        sip = try container.decodeIfPresent(CallingSettingsCallingSip.self, forKey: .sip)
        video = try container.decodeIfPresent(CallingSettingsCallingVideo.self, forKey: .video)
        audio = try container.decodeIfPresent(CallingSettingsCallingAudio.self, forKey: .audio)
        restrictions = try container.decodeIfPresent([String: AnyCodable].self, forKey: .restrictions)
        ipAddresses = try container.decodeIfPresent([String: AnyCodable].self, forKey: .ipAddresses)
        callIcons = try container.decodeIfPresent([String: AnyCodable].self, forKey: .callIcons)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("status")
        nonAdditionalPropertyKeys.insert("call_icon_visibility")
        nonAdditionalPropertyKeys.insert("callback_permission_status")
        nonAdditionalPropertyKeys.insert("srtp_key_exchange_protocol")
        nonAdditionalPropertyKeys.insert("call_hours")
        nonAdditionalPropertyKeys.insert("sip")
        nonAdditionalPropertyKeys.insert("video")
        nonAdditionalPropertyKeys.insert("audio")
        nonAdditionalPropertyKeys.insert("restrictions")
        nonAdditionalPropertyKeys.insert("ip_addresses")
        nonAdditionalPropertyKeys.insert("call_icons")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

