//
// ConversationalAutomation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ConversationalAutomation: Codable, JSONEncodable, Hashable {

    public static let promptsRule = ArrayRule(minItems: nil, maxItems: 4, uniqueItems: false)
    public static let commandsRule = ArrayRule(minItems: nil, maxItems: 30, uniqueItems: false)
    /** Enable the automatic welcome message for new conversations */
    public var enableWelcomeMessage: Bool?
    /** Ice-breaker prompt strings (max 4, each ≤ 80 characters) */
    public var prompts: [String]?
    /** Slash commands shown in WhatsApp */
    public var commands: [ConversationalAutomationCommandsInner]?

    public init(enableWelcomeMessage: Bool? = nil, prompts: [String]? = nil, commands: [ConversationalAutomationCommandsInner]? = nil) {
        self.enableWelcomeMessage = enableWelcomeMessage
        self.prompts = prompts
        self.commands = commands
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enableWelcomeMessage = "enable_welcome_message"
        case prompts
        case commands
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(enableWelcomeMessage, forKey: .enableWelcomeMessage)
        try container.encodeIfPresent(prompts, forKey: .prompts)
        try container.encodeIfPresent(commands, forKey: .commands)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        enableWelcomeMessage = try container.decodeIfPresent(Bool.self, forKey: .enableWelcomeMessage)
        prompts = try container.decodeIfPresent([String].self, forKey: .prompts)
        commands = try container.decodeIfPresent([ConversationalAutomationCommandsInner].self, forKey: .commands)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("enable_welcome_message")
        nonAdditionalPropertyKeys.insert("prompts")
        nonAdditionalPropertyKeys.insert("commands")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

