//
// ConversationalAutomationCommandsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ConversationalAutomationCommandsInner: Codable, JSONEncodable, Hashable {

    public static let commandNameRule = StringRule(minLength: nil, maxLength: 32, pattern: nil)
    public static let commandDescriptionRule = StringRule(minLength: nil, maxLength: 256, pattern: nil)
    public var commandName: String
    public var commandDescription: String

    public init(commandName: String, commandDescription: String) {
        self.commandName = commandName
        self.commandDescription = commandDescription
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case commandName = "command_name"
        case commandDescription = "command_description"
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(commandName, forKey: .commandName)
        try container.encode(commandDescription, forKey: .commandDescription)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        commandName = try container.decode(String.self, forKey: .commandName)
        commandDescription = try container.decode(String.self, forKey: .commandDescription)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("command_name")
        nonAdditionalPropertyKeys.insert("command_description")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

