//
// CreateCommerceRequestParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCommerceRequestParams: Codable, JSONEncodable, Hashable {

    /** Enable cart */
    public var isCartEnabled: Bool
    /** Show catalog storefront icon */
    public var isCatalogVisible: Bool

    public init(isCartEnabled: Bool, isCatalogVisible: Bool) {
        self.isCartEnabled = isCartEnabled
        self.isCatalogVisible = isCatalogVisible
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isCartEnabled = "is_cart_enabled"
        case isCatalogVisible = "is_catalog_visible"
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isCartEnabled, forKey: .isCartEnabled)
        try container.encode(isCatalogVisible, forKey: .isCatalogVisible)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        isCartEnabled = try container.decode(Bool.self, forKey: .isCartEnabled)
        isCatalogVisible = try container.decode(Bool.self, forKey: .isCatalogVisible)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("is_cart_enabled")
        nonAdditionalPropertyKeys.insert("is_catalog_visible")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

