//
// GetCommerce200ResponseInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetCommerce200ResponseInner: Codable, JSONEncodable, Hashable {

    /** Catalog id */
    public var id: String?
    /** Whether the cart is enabled */
    public var isCartEnabled: Bool?
    /** Whether the catalog storefront icon is shown */
    public var isCatalogVisible: Bool?

    public init(id: String? = nil, isCartEnabled: Bool? = nil, isCatalogVisible: Bool? = nil) {
        self.id = id
        self.isCartEnabled = isCartEnabled
        self.isCatalogVisible = isCatalogVisible
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case isCartEnabled = "is_cart_enabled"
        case isCatalogVisible = "is_catalog_visible"
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(isCartEnabled, forKey: .isCartEnabled)
        try container.encodeIfPresent(isCatalogVisible, forKey: .isCatalogVisible)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        id = try container.decodeIfPresent(String.self, forKey: .id)
        isCartEnabled = try container.decodeIfPresent(Bool.self, forKey: .isCartEnabled)
        isCatalogVisible = try container.decodeIfPresent(Bool.self, forKey: .isCatalogVisible)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("id")
        nonAdditionalPropertyKeys.insert("is_cart_enabled")
        nonAdditionalPropertyKeys.insert("is_catalog_visible")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension GetCommerce200ResponseInner: Identifiable {}
