//
// InitiateCallRequestSession.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** WebRTC SDP session (required for connect / pre_accept / accept) */
public struct InitiateCallRequestSession: Codable, JSONEncodable, Hashable {

    public enum SdpType: String, Codable, CaseIterable {
        case offer = "offer"
        case answer = "answer"
    }
    /** offer for outbound connect; answer for pre_accept/accept */
    public var sdpType: SdpType
    /** Full SDP (RFC 8866). Replace placeholders with SDP from your WebRTC stack. Must negotiate ICE, DTLS-SRTP, and OPUS for WhatsApp media.  */
    public var sdp: String

    public init(sdpType: SdpType, sdp: String) {
        self.sdpType = sdpType
        self.sdp = sdp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sdpType = "sdp_type"
        case sdp
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sdpType, forKey: .sdpType)
        try container.encode(sdp, forKey: .sdp)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        sdpType = try container.decode(SdpType.self, forKey: .sdpType)
        sdp = try container.decode(String.self, forKey: .sdp)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("sdp_type")
        nonAdditionalPropertyKeys.insert("sdp")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

