//
// InitiateCallResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Successful call action response from upstream, returned as-is. On empty upstream body, 1msg may return &#x60;{ \&quot;result\&quot;: \&quot;success\&quot; }&#x60;. Upstream failures are often wrapped as HTTP 200 &#x60;{ \&quot;response\&quot;: { \&quot;error\&quot;: \&quot;...\&quot; } }&#x60;.  */
public struct InitiateCallResponse: Codable, JSONEncodable, Hashable {

    public var messagingProduct: String?
    public var success: Bool?
    /** Present on outbound `connect` — contains the new call id */
    public var calls: [InitiateCallResponseCallsInner]?
    /** Legacy success marker when upstream returns an empty body */
    public var result: String?
    public var response: InitiateCallResponseResponse?

    public init(messagingProduct: String? = nil, success: Bool? = nil, calls: [InitiateCallResponseCallsInner]? = nil, result: String? = nil, response: InitiateCallResponseResponse? = nil) {
        self.messagingProduct = messagingProduct
        self.success = success
        self.calls = calls
        self.result = result
        self.response = response
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case messagingProduct = "messaging_product"
        case success
        case calls
        case result
        case response
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(messagingProduct, forKey: .messagingProduct)
        try container.encodeIfPresent(success, forKey: .success)
        try container.encodeIfPresent(calls, forKey: .calls)
        try container.encodeIfPresent(result, forKey: .result)
        try container.encodeIfPresent(response, forKey: .response)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        messagingProduct = try container.decodeIfPresent(String.self, forKey: .messagingProduct)
        success = try container.decodeIfPresent(Bool.self, forKey: .success)
        calls = try container.decodeIfPresent([InitiateCallResponseCallsInner].self, forKey: .calls)
        result = try container.decodeIfPresent(String.self, forKey: .result)
        response = try container.decodeIfPresent(InitiateCallResponseResponse.self, forKey: .response)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("messaging_product")
        nonAdditionalPropertyKeys.insert("success")
        nonAdditionalPropertyKeys.insert("calls")
        nonAdditionalPropertyKeys.insert("result")
        nonAdditionalPropertyKeys.insert("response")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

