//
// InitiateCallRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Call action payload for &#x60;POST /initiateCall&#x60; (proxies upstream &#x60;POST /calling/calls&#x60;).  Despite the path name, this endpoint handles **all** call actions — not only outbound connect.  ## Required fields by &#x60;action&#x60;  | action | Required | &#x60;session&#x60; | |--------|----------|-----------| | &#x60;connect&#x60; (outbound) | &#x60;messaging_product&#x60;, &#x60;to&#x60;, &#x60;action&#x60; | &#x60;sdp_type: offer&#x60; + business WebRTC SDP | | &#x60;pre_accept&#x60; | &#x60;messaging_product&#x60;, &#x60;call_id&#x60;, &#x60;action&#x60; | &#x60;sdp_type: answer&#x60; (WebRTC-generated) | | &#x60;accept&#x60; | &#x60;messaging_product&#x60;, &#x60;call_id&#x60;, &#x60;action&#x60; | &#x60;sdp_type: answer&#x60; (WebRTC-generated) | | &#x60;reject&#x60; | &#x60;messaging_product&#x60;, &#x60;call_id&#x60;, &#x60;action&#x60; | none | | &#x60;terminate&#x60; | &#x60;messaging_product&#x60;, &#x60;call_id&#x60;, &#x60;action&#x60; | none |  **Critical:** For &#x60;pre_accept&#x60; / &#x60;accept&#x60;, &#x60;session.sdp&#x60; must be a **WebRTC-generated SDP answer**. Do not echo Meta&#39;s offer SDP back. Postman alone cannot establish real media — you need a WebRTC (or SIP) stack.  */
public struct InitiateCallRequest: Codable, JSONEncodable, Hashable {

    public enum MessagingProduct: String, Codable, CaseIterable {
        case whatsapp = "whatsapp"
    }
    public enum Action: String, Codable, CaseIterable {
        case connect = "connect"
        case preAccept = "pre_accept"
        case accept = "accept"
        case reject = "reject"
        case terminate = "terminate"
    }
    public static let bizOpaqueCallbackDataRule = StringRule(minLength: nil, maxLength: 512, pattern: nil)
    /** Must be `whatsapp` */
    public var messagingProduct: MessagingProduct
    /** Call control action */
    public var action: Action
    /** WhatsApp call id from the inbound/outbound calls webhook (`calls[].id`). Required for `pre_accept`, `accept`, `reject`, `terminate`.  */
    public var callId: String?
    /** Recipient WhatsApp user phone (digits, country code, no +). Required for outbound `connect`.  */
    public var to: String?
    /** Optional opaque string echoed on later call webhooks for correlation */
    public var bizOpaqueCallbackData: String?
    public var session: InitiateCallRequestSession?

    public init(messagingProduct: MessagingProduct, action: Action, callId: String? = nil, to: String? = nil, bizOpaqueCallbackData: String? = nil, session: InitiateCallRequestSession? = nil) {
        self.messagingProduct = messagingProduct
        self.action = action
        self.callId = callId
        self.to = to
        self.bizOpaqueCallbackData = bizOpaqueCallbackData
        self.session = session
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case messagingProduct = "messaging_product"
        case action
        case callId = "call_id"
        case to
        case bizOpaqueCallbackData = "biz_opaque_callback_data"
        case session
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(messagingProduct, forKey: .messagingProduct)
        try container.encode(action, forKey: .action)
        try container.encodeIfPresent(callId, forKey: .callId)
        try container.encodeIfPresent(to, forKey: .to)
        try container.encodeIfPresent(bizOpaqueCallbackData, forKey: .bizOpaqueCallbackData)
        try container.encodeIfPresent(session, forKey: .session)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        messagingProduct = try container.decode(MessagingProduct.self, forKey: .messagingProduct)
        action = try container.decode(Action.self, forKey: .action)
        callId = try container.decodeIfPresent(String.self, forKey: .callId)
        to = try container.decodeIfPresent(String.self, forKey: .to)
        bizOpaqueCallbackData = try container.decodeIfPresent(String.self, forKey: .bizOpaqueCallbackData)
        session = try container.decodeIfPresent(InitiateCallRequestSession.self, forKey: .session)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("messaging_product")
        nonAdditionalPropertyKeys.insert("action")
        nonAdditionalPropertyKeys.insert("call_id")
        nonAdditionalPropertyKeys.insert("to")
        nonAdditionalPropertyKeys.insert("biz_opaque_callback_data")
        nonAdditionalPropertyKeys.insert("session")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

