//
// ListFlows200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListFlows200Response: Codable, JSONEncodable, Hashable {

    public var items: [[String: AnyCodable]]?
    public var paging: [String: AnyCodable]?
    public var count: Int?
    public var total: Int?
    /** Error details returned by the provider. May be a string or a JSON object. */
    public var error: AnyCodable?

    public init(items: [[String: AnyCodable]]? = nil, paging: [String: AnyCodable]? = nil, count: Int? = nil, total: Int? = nil, error: AnyCodable? = nil) {
        self.items = items
        self.paging = paging
        self.count = count
        self.total = total
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
        case paging
        case count
        case total
        case error
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(items, forKey: .items)
        try container.encodeIfPresent(paging, forKey: .paging)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(error, forKey: .error)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        items = try container.decodeIfPresent([[String: AnyCodable]].self, forKey: .items)
        paging = try container.decodeIfPresent([String: AnyCodable].self, forKey: .paging)
        count = try container.decodeIfPresent(Int.self, forKey: .count)
        total = try container.decodeIfPresent(Int.self, forKey: .total)
        error = try container.decodeIfPresent(AnyCodable.self, forKey: .error)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("items")
        nonAdditionalPropertyKeys.insert("paging")
        nonAdditionalPropertyKeys.insert("count")
        nonAdditionalPropertyKeys.insert("total")
        nonAdditionalPropertyKeys.insert("error")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

