//
// ListTemplates200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListTemplates200Response: Codable, JSONEncodable, Hashable {

    public var total: Int?
    public var templates: [[String: AnyCodable]]?
    public var error: [String: AnyCodable]?

    public init(total: Int? = nil, templates: [[String: AnyCodable]]? = nil, error: [String: AnyCodable]? = nil) {
        self.total = total
        self.templates = templates
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case templates
        case error
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(templates, forKey: .templates)
        try container.encodeIfPresent(error, forKey: .error)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        total = try container.decodeIfPresent(Int.self, forKey: .total)
        templates = try container.decodeIfPresent([[String: AnyCodable]].self, forKey: .templates)
        error = try container.decodeIfPresent([String: AnyCodable].self, forKey: .error)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("total")
        nonAdditionalPropertyKeys.insert("templates")
        nonAdditionalPropertyKeys.insert("error")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

