//
// ProfileInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** WhatsApp Business profile information */
public struct ProfileInfo: Codable, JSONEncodable, Hashable {

    public enum Vertical: String, Codable, CaseIterable {
        case automotive = "Automotive"
        case beautyCommaSpaAndSalon = "Beauty, Spa and Salon"
        case clothingAndApparel = "Clothing and Apparel"
        case education = "Education"
        case entertainment = "Entertainment"
        case eventPlanningAndService = "Event Planning and Service"
        case financeAndBanking = "Finance and Banking"
        case foodAndGrocery = "Food and Grocery"
        case publicService = "Public Service"
        case hotelAndLodging = "Hotel and Lodging"
        case medicalAndHealth = "Medical and Health"
        case nonProfit = "Non-profit"
        case professionalServices = "Professional Services"
        case shoppingAndRetail = "Shopping and Retail"
        case travelAndTransportation = "Travel and Transportation"
        case restaurant = "Restaurant"
        case other = "Other"
    }
    /** Profile's About section */
    public var about: String?
    /** Address of the business */
    public var address: String?
    /** Description of the business */
    public var description: String?
    /** Business email */
    public var email: String?
    /** Linked phone number */
    public var phone: String?
    /** Industry of the business */
    public var vertical: Vertical?
    /** Profile photo URL */
    public var photo: String?
    public var websites: [String]?

    public init(about: String? = nil, address: String? = nil, description: String? = nil, email: String? = nil, phone: String? = nil, vertical: Vertical? = nil, photo: String? = nil, websites: [String]? = nil) {
        self.about = about
        self.address = address
        self.description = description
        self.email = email
        self.phone = phone
        self.vertical = vertical
        self.photo = photo
        self.websites = websites
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case about
        case address
        case description
        case email
        case phone
        case vertical
        case photo
        case websites
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(about, forKey: .about)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(vertical, forKey: .vertical)
        try container.encodeIfPresent(photo, forKey: .photo)
        try container.encodeIfPresent(websites, forKey: .websites)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        about = try container.decodeIfPresent(String.self, forKey: .about)
        address = try container.decodeIfPresent(String.self, forKey: .address)
        description = try container.decodeIfPresent(String.self, forKey: .description)
        email = try container.decodeIfPresent(String.self, forKey: .email)
        phone = try container.decodeIfPresent(String.self, forKey: .phone)
        vertical = try container.decodeIfPresent(Vertical.self, forKey: .vertical)
        photo = try container.decodeIfPresent(String.self, forKey: .photo)
        websites = try container.decodeIfPresent([String].self, forKey: .websites)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("about")
        nonAdditionalPropertyKeys.insert("address")
        nonAdditionalPropertyKeys.insert("description")
        nonAdditionalPropertyKeys.insert("email")
        nonAdditionalPropertyKeys.insert("phone")
        nonAdditionalPropertyKeys.insert("vertical")
        nonAdditionalPropertyKeys.insert("photo")
        nonAdditionalPropertyKeys.insert("websites")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

