//
// SendButtonRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendButtonRequest: Codable, JSONEncodable, Hashable {

    public var phone: String?
    public var body: String?
    public var footer: String?
    public var sections: [SendButtonRequestSectionsInner]?

    public init(phone: String? = nil, body: String? = nil, footer: String? = nil, sections: [SendButtonRequestSectionsInner]? = nil) {
        self.phone = phone
        self.body = body
        self.footer = footer
        self.sections = sections
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case phone
        case body
        case footer
        case sections
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(body, forKey: .body)
        try container.encodeIfPresent(footer, forKey: .footer)
        try container.encodeIfPresent(sections, forKey: .sections)
    }
}

