//
// SendFlowRequest1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendFlowRequest1: Codable, JSONEncodable, Hashable {

    public enum FlowAction: String, Codable, CaseIterable {
        case navigate = "navigate"
        case dataExchange = "data_exchange"
    }
    public enum Mode: String, Codable, CaseIterable {
        case draft = "draft"
        case published = "published"
    }
    public var body: String
    public var header: SendFlowRequest1Header?
    public var footer: String?
    public var flowId: String
    public var flowToken: String
    public var flowCta: String
    public var flowAction: FlowAction?
    public var flowActionPayload: AnyCodable?
    public var flowMessageVersion: String?
    public var mode: Mode?
    public var flowActionData: AnyCodable?
    public var flowActionScreen: String?
    public var quotedMsgId: String?
    public var chatId: String?
    public var phone: Int?

    public init(body: String, header: SendFlowRequest1Header? = nil, footer: String? = nil, flowId: String, flowToken: String, flowCta: String, flowAction: FlowAction? = nil, flowActionPayload: AnyCodable? = nil, flowMessageVersion: String? = nil, mode: Mode? = nil, flowActionData: AnyCodable? = nil, flowActionScreen: String? = nil, quotedMsgId: String? = nil, chatId: String? = nil, phone: Int? = nil) {
        self.body = body
        self.header = header
        self.footer = footer
        self.flowId = flowId
        self.flowToken = flowToken
        self.flowCta = flowCta
        self.flowAction = flowAction
        self.flowActionPayload = flowActionPayload
        self.flowMessageVersion = flowMessageVersion
        self.mode = mode
        self.flowActionData = flowActionData
        self.flowActionScreen = flowActionScreen
        self.quotedMsgId = quotedMsgId
        self.chatId = chatId
        self.phone = phone
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case body
        case header
        case footer
        case flowId
        case flowToken
        case flowCta
        case flowAction
        case flowActionPayload
        case flowMessageVersion
        case mode
        case flowActionData
        case flowActionScreen
        case quotedMsgId
        case chatId
        case phone
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(body, forKey: .body)
        try container.encodeIfPresent(header, forKey: .header)
        try container.encodeIfPresent(footer, forKey: .footer)
        try container.encode(flowId, forKey: .flowId)
        try container.encode(flowToken, forKey: .flowToken)
        try container.encode(flowCta, forKey: .flowCta)
        try container.encodeIfPresent(flowAction, forKey: .flowAction)
        try container.encodeIfPresent(flowActionPayload, forKey: .flowActionPayload)
        try container.encodeIfPresent(flowMessageVersion, forKey: .flowMessageVersion)
        try container.encodeIfPresent(mode, forKey: .mode)
        try container.encodeIfPresent(flowActionData, forKey: .flowActionData)
        try container.encodeIfPresent(flowActionScreen, forKey: .flowActionScreen)
        try container.encodeIfPresent(quotedMsgId, forKey: .quotedMsgId)
        try container.encodeIfPresent(chatId, forKey: .chatId)
        try container.encodeIfPresent(phone, forKey: .phone)
    }
}

