//
// SendListRequestSectionsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendListRequestSectionsInner: Codable, JSONEncodable, Hashable {

    public var title: String?
    public var rows: [SendListRequestSectionsInnerRowsInner]?

    public init(title: String? = nil, rows: [SendListRequestSectionsInnerRowsInner]? = nil) {
        self.title = title
        self.rows = rows
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case rows
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(rows, forKey: .rows)
    }
}

