//
// SendMessageRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request body for sending a text message */
public struct SendMessageRequest: Codable, JSONEncodable, Hashable {

    public static let bodyRule = StringRule(minLength: 1, maxLength: 4096, pattern: nil)
    public static let quotedMsgIdRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^wamid\\..+$/")
    public static let chatIdRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^[0-9]+@[cg]\\.us$/")
    public static let phoneRule = NumericRule<Int>(minimum: 1000000000, exclusiveMinimum: false, maximum: 999999999999999, exclusiveMaximum: false, multipleOf: nil)
    /** Message text, UTF-8 or UTF-16 string with emoji */
    public var body: String
    /** Message ID to quote/reply to (Cloud API wamid) */
    public var quotedMsgId: String?
    /** Chat ID in format: phone@c.us (individual) or phone@g.us (group) */
    public var chatId: String?
    /** Phone number starting with country code (alternative to chatId) */
    public var phone: Int?

    public init(body: String, quotedMsgId: String? = nil, chatId: String? = nil, phone: Int? = nil) {
        self.body = body
        self.quotedMsgId = quotedMsgId
        self.chatId = chatId
        self.phone = phone
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case body
        case quotedMsgId
        case chatId
        case phone
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(body, forKey: .body)
        try container.encodeIfPresent(quotedMsgId, forKey: .quotedMsgId)
        try container.encodeIfPresent(chatId, forKey: .chatId)
        try container.encodeIfPresent(phone, forKey: .phone)
    }
}

