//
// SendContactRequestContactsInnerOrg.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendContactRequestContactsInnerOrg: Codable, JSONEncodable, Hashable {

    public var company: String?
    public var department: String?
    public var title: String?

    public init(company: String? = nil, department: String? = nil, title: String? = nil) {
        self.company = company
        self.department = department
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case company
        case department
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(company, forKey: .company)
        try container.encodeIfPresent(department, forKey: .department)
        try container.encodeIfPresent(title, forKey: .title)
    }
}

