//
// SendContactRequestContactsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendContactRequestContactsInner: Codable, JSONEncodable, Hashable {

    public var name: SendContactRequestContactsInnerName?
    public var birthday: String?
    public var addresses: [AnyCodable]?
    public var emails: [AnyCodable]?
    public var org: SendContactRequestContactsInnerOrg?
    public var phones: [SendContactRequestContactsInnerPhonesInner]?
    public var urls: [AnyCodable]?

    public init(name: SendContactRequestContactsInnerName? = nil, birthday: String? = nil, addresses: [AnyCodable]? = nil, emails: [AnyCodable]? = nil, org: SendContactRequestContactsInnerOrg? = nil, phones: [SendContactRequestContactsInnerPhonesInner]? = nil, urls: [AnyCodable]? = nil) {
        self.name = name
        self.birthday = birthday
        self.addresses = addresses
        self.emails = emails
        self.org = org
        self.phones = phones
        self.urls = urls
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case birthday
        case addresses
        case emails
        case org
        case phones
        case urls
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(birthday, forKey: .birthday)
        try container.encodeIfPresent(addresses, forKey: .addresses)
        try container.encodeIfPresent(emails, forKey: .emails)
        try container.encodeIfPresent(org, forKey: .org)
        try container.encodeIfPresent(phones, forKey: .phones)
        try container.encodeIfPresent(urls, forKey: .urls)
    }
}

