//
// SendFileRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Send file by URL/base64 or by mediaId */
public struct SendFileRequest: Codable, JSONEncodable, Hashable {

    public enum MediaType: String, Codable, CaseIterable {
        case image = "image"
        case video = "video"
        case audio = "audio"
        case document = "document"
    }
    public static let captionRule = StringRule(minLength: nil, maxLength: 1024, pattern: nil)
    /** File source (required unless mediaId is set): - HTTP/HTTPS URL - Base64 data URI  */
    public var body: String?
    /** File name with extension (required with body, not with mediaId) */
    public var filename: String?
    /** WABA media id from uploadMedia (alternative to body) */
    public var mediaId: String?
    /** Required when using mediaId */
    public var mediaType: MediaType?
    /** Native WhatsApp voice note (audio/ogg only) */
    public var voice: Bool?
    public var caption: String?
    public var quotedMsgId: String?
    public var chatId: String?
    public var phone: Int?

    public init(body: String? = nil, filename: String? = nil, mediaId: String? = nil, mediaType: MediaType? = nil, voice: Bool? = nil, caption: String? = nil, quotedMsgId: String? = nil, chatId: String? = nil, phone: Int? = nil) {
        self.body = body
        self.filename = filename
        self.mediaId = mediaId
        self.mediaType = mediaType
        self.voice = voice
        self.caption = caption
        self.quotedMsgId = quotedMsgId
        self.chatId = chatId
        self.phone = phone
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case body
        case filename
        case mediaId
        case mediaType
        case voice
        case caption
        case quotedMsgId
        case chatId
        case phone
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(body, forKey: .body)
        try container.encodeIfPresent(filename, forKey: .filename)
        try container.encodeIfPresent(mediaId, forKey: .mediaId)
        try container.encodeIfPresent(mediaType, forKey: .mediaType)
        try container.encodeIfPresent(voice, forKey: .voice)
        try container.encodeIfPresent(caption, forKey: .caption)
        try container.encodeIfPresent(quotedMsgId, forKey: .quotedMsgId)
        try container.encodeIfPresent(chatId, forKey: .chatId)
        try container.encodeIfPresent(phone, forKey: .phone)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        body = try container.decodeIfPresent(String.self, forKey: .body)
        filename = try container.decodeIfPresent(String.self, forKey: .filename)
        mediaId = try container.decodeIfPresent(String.self, forKey: .mediaId)
        mediaType = try container.decodeIfPresent(MediaType.self, forKey: .mediaType)
        voice = try container.decodeIfPresent(Bool.self, forKey: .voice)
        caption = try container.decodeIfPresent(String.self, forKey: .caption)
        quotedMsgId = try container.decodeIfPresent(String.self, forKey: .quotedMsgId)
        chatId = try container.decodeIfPresent(String.self, forKey: .chatId)
        phone = try container.decodeIfPresent(Int.self, forKey: .phone)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("body")
        nonAdditionalPropertyKeys.insert("filename")
        nonAdditionalPropertyKeys.insert("mediaId")
        nonAdditionalPropertyKeys.insert("mediaType")
        nonAdditionalPropertyKeys.insert("voice")
        nonAdditionalPropertyKeys.insert("caption")
        nonAdditionalPropertyKeys.insert("quotedMsgId")
        nonAdditionalPropertyKeys.insert("chatId")
        nonAdditionalPropertyKeys.insert("phone")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

