//
// SendContactRequestContactsInnerName.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendContactRequestContactsInnerName: Codable, JSONEncodable, Hashable {

    public var formattedName: String?
    public var firstName: String?
    public var lastName: String?
    public var middleName: String?
    public var suffix: String?
    public var _prefix: String?

    public init(formattedName: String? = nil, firstName: String? = nil, lastName: String? = nil, middleName: String? = nil, suffix: String? = nil, _prefix: String? = nil) {
        self.formattedName = formattedName
        self.firstName = firstName
        self.lastName = lastName
        self.middleName = middleName
        self.suffix = suffix
        self._prefix = _prefix
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case formattedName = "formatted_name"
        case firstName = "first_name"
        case lastName = "last_name"
        case middleName = "middle_name"
        case suffix
        case _prefix = "prefix"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(formattedName, forKey: .formattedName)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(middleName, forKey: .middleName)
        try container.encodeIfPresent(suffix, forKey: .suffix)
        try container.encodeIfPresent(_prefix, forKey: ._prefix)
    }
}

