//
// SendAddressMessageRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendAddressMessageRequest: Codable, JSONEncodable, Hashable {

    public enum Country: String, Codable, CaseIterable {
        case _in = "IN"
        case sg = "SG"
    }
    /** Recipient phone (E.164 digits, no +). Must match country. */
    public var phone: Int?
    public var chatId: String?
    /** Body text shown with the address request */
    public var body: String
    /** Address form country. Defaults to IN if omitted. */
    public var country: Country?
    /** Optional prefilled address fields */
    public var values: [String: AnyCodable]?
    /** Optional previously saved addresses for the user */
    public var savedAddresses: [[String: AnyCodable]]?
    /** Optional field validation errors when re-prompting */
    public var validationErrors: [String: AnyCodable]?
    public var quotedMsgId: String?

    public init(phone: Int? = nil, chatId: String? = nil, body: String, country: Country? = nil, values: [String: AnyCodable]? = nil, savedAddresses: [[String: AnyCodable]]? = nil, validationErrors: [String: AnyCodable]? = nil, quotedMsgId: String? = nil) {
        self.phone = phone
        self.chatId = chatId
        self.body = body
        self.country = country
        self.values = values
        self.savedAddresses = savedAddresses
        self.validationErrors = validationErrors
        self.quotedMsgId = quotedMsgId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case phone
        case chatId
        case body
        case country
        case values
        case savedAddresses = "saved_addresses"
        case validationErrors = "validation_errors"
        case quotedMsgId
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(chatId, forKey: .chatId)
        try container.encode(body, forKey: .body)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(values, forKey: .values)
        try container.encodeIfPresent(savedAddresses, forKey: .savedAddresses)
        try container.encodeIfPresent(validationErrors, forKey: .validationErrors)
        try container.encodeIfPresent(quotedMsgId, forKey: .quotedMsgId)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        phone = try container.decodeIfPresent(Int.self, forKey: .phone)
        chatId = try container.decodeIfPresent(String.self, forKey: .chatId)
        body = try container.decode(String.self, forKey: .body)
        country = try container.decodeIfPresent(Country.self, forKey: .country)
        values = try container.decodeIfPresent([String: AnyCodable].self, forKey: .values)
        savedAddresses = try container.decodeIfPresent([[String: AnyCodable]].self, forKey: .savedAddresses)
        validationErrors = try container.decodeIfPresent([String: AnyCodable].self, forKey: .validationErrors)
        quotedMsgId = try container.decodeIfPresent(String.self, forKey: .quotedMsgId)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("phone")
        nonAdditionalPropertyKeys.insert("chatId")
        nonAdditionalPropertyKeys.insert("body")
        nonAdditionalPropertyKeys.insert("country")
        nonAdditionalPropertyKeys.insert("values")
        nonAdditionalPropertyKeys.insert("saved_addresses")
        nonAdditionalPropertyKeys.insert("validation_errors")
        nonAdditionalPropertyKeys.insert("quotedMsgId")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

