//
// SendContactRequestContactsInnerPhonesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendContactRequestContactsInnerPhonesInner: Codable, JSONEncodable, Hashable {

    public var phone: String?
    public var type: String?
    public var waId: String?

    public init(phone: String? = nil, type: String? = nil, waId: String? = nil) {
        self.phone = phone
        self.type = type
        self.waId = waId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case phone
        case type
        case waId = "wa_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(waId, forKey: .waId)
    }
}

