//
// SendLocationRequestRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendLocationRequestRequest: Codable, JSONEncodable, Hashable {

    public var phone: String?
    public var body: String?

    public init(phone: String? = nil, body: String? = nil) {
        self.phone = phone
        self.body = body
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case phone
        case body
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(body, forKey: .body)
    }
}

