//
// SendCtaUrlRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendCtaUrlRequest: Codable, JSONEncodable, Hashable {

    public var phone: Int?
    public var chatId: String?
    public var body: String
    /** Button label */
    public var displayText: String
    public var url: String
    public var header: [String: AnyCodable]?
    public var footer: String?
    public var quotedMsgId: String?

    public init(phone: Int? = nil, chatId: String? = nil, body: String, displayText: String, url: String, header: [String: AnyCodable]? = nil, footer: String? = nil, quotedMsgId: String? = nil) {
        self.phone = phone
        self.chatId = chatId
        self.body = body
        self.displayText = displayText
        self.url = url
        self.header = header
        self.footer = footer
        self.quotedMsgId = quotedMsgId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case phone
        case chatId
        case body
        case displayText
        case url
        case header
        case footer
        case quotedMsgId
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(chatId, forKey: .chatId)
        try container.encode(body, forKey: .body)
        try container.encode(displayText, forKey: .displayText)
        try container.encode(url, forKey: .url)
        try container.encodeIfPresent(header, forKey: .header)
        try container.encodeIfPresent(footer, forKey: .footer)
        try container.encodeIfPresent(quotedMsgId, forKey: .quotedMsgId)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        phone = try container.decodeIfPresent(Int.self, forKey: .phone)
        chatId = try container.decodeIfPresent(String.self, forKey: .chatId)
        body = try container.decode(String.self, forKey: .body)
        displayText = try container.decode(String.self, forKey: .displayText)
        url = try container.decode(String.self, forKey: .url)
        header = try container.decodeIfPresent([String: AnyCodable].self, forKey: .header)
        footer = try container.decodeIfPresent(String.self, forKey: .footer)
        quotedMsgId = try container.decodeIfPresent(String.self, forKey: .quotedMsgId)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("phone")
        nonAdditionalPropertyKeys.insert("chatId")
        nonAdditionalPropertyKeys.insert("body")
        nonAdditionalPropertyKeys.insert("displayText")
        nonAdditionalPropertyKeys.insert("url")
        nonAdditionalPropertyKeys.insert("header")
        nonAdditionalPropertyKeys.insert("footer")
        nonAdditionalPropertyKeys.insert("quotedMsgId")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

