//
// CatalogAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class CatalogAPI {

    /**
     Set Commerce Settings
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter createCommerceRequest: (body)  
     - returns: CreateCommerce200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createCommerce(token: String, createCommerceRequest: CreateCommerceRequest) async throws -> CreateCommerce200Response {
        return try await createCommerceWithRequestBuilder(token: token, createCommerceRequest: createCommerceRequest).execute().body
    }

    /**
     Set Commerce Settings
     - POST /commerce
     - Update catalog/cart commerce settings via the `params` object.  - `params.is_catalog_visible` — show catalog storefront icon (`true`) or hide it (`false`). - `params.is_cart_enabled` — enable cart (`true`) or disable it (`false`).  Blocked when the channel subscription limit is exceeded. Requires a commerce-capable channel (Cloud Functions `/commerceWAV2`). 
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter createCommerceRequest: (body)  
     - returns: RequestBuilder<CreateCommerce200Response> 
     */
    open class func createCommerceWithRequestBuilder(token: String, createCommerceRequest: CreateCommerceRequest) -> RequestBuilder<CreateCommerce200Response> {
        let localVariablePath = "/commerce"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createCommerceRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateCommerce200Response>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Commerce Settings
     
     - parameter token: (query) JWT token or API key for authorization 
     - returns: [GetCommerce200ResponseInner]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getCommerce(token: String) async throws -> [GetCommerce200ResponseInner] {
        return try await getCommerceWithRequestBuilder(token: token).execute().body
    }

    /**
     Get Commerce Settings
     - GET /commerce
     - Returns catalog/cart commerce settings for the channel.  - `is_catalog_visible` — show catalog storefront icon (`true`) or hide it (`false`). - `is_cart_enabled` — enable cart (`true`) or disable it (`false`). 
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - returns: RequestBuilder<[GetCommerce200ResponseInner]> 
     */
    open class func getCommerceWithRequestBuilder(token: String) -> RequestBuilder<[GetCommerce200ResponseInner]> {
        let localVariablePath = "/commerce"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[GetCommerce200ResponseInner]>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
