//
// FlowsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class FlowsAPI {

    /**
     Create Flow
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter wabaAccountId: (query)  (optional)
     - returns: CreateGroups200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createFlows(token: String, wabaAccountId: String? = nil) async throws -> CreateGroups200Response {
        return try await createFlowsWithRequestBuilder(token: token, wabaAccountId: wabaAccountId).execute().body
    }

    /**
     Create Flow
     - POST /flows
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter wabaAccountId: (query)  (optional)
     - returns: RequestBuilder<CreateGroups200Response> 
     */
    open class func createFlowsWithRequestBuilder(token: String, wabaAccountId: String? = nil) -> RequestBuilder<CreateGroups200Response> {
        let localVariablePath = "/flows"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
            "wabaAccountId": (wrappedValue: wabaAccountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateGroups200Response>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Deprecate Flow
     
     - parameter flowId: (path) Flow ID 
     - parameter token: (query) JWT token or API key for authorization 
     - parameter wabaAccountId: (query)  (optional)
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createFlowsFlowIdDeprecate(flowId: String, token: String, wabaAccountId: String? = nil) async throws -> [String: AnyCodable] {
        return try await createFlowsFlowIdDeprecateWithRequestBuilder(flowId: flowId, token: token, wabaAccountId: wabaAccountId).execute().body
    }

    /**
     Deprecate Flow
     - POST /flows/{flowId}/deprecate
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter flowId: (path) Flow ID 
     - parameter token: (query) JWT token or API key for authorization 
     - parameter wabaAccountId: (query)  (optional)
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func createFlowsFlowIdDeprecateWithRequestBuilder(flowId: String, token: String, wabaAccountId: String? = nil) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/flows/{flowId}/deprecate"
        let flowIdPreEscape = "\(APIHelper.mapValueToPathItem(flowId))"
        let flowIdPostEscape = flowIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{flowId}", with: flowIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
            "wabaAccountId": (wrappedValue: wabaAccountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Publish Flow
     
     - parameter flowId: (path) Flow ID 
     - parameter token: (query) JWT token or API key for authorization 
     - parameter wabaAccountId: (query)  (optional)
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createFlowsFlowIdPublish(flowId: String, token: String, wabaAccountId: String? = nil) async throws -> [String: AnyCodable] {
        return try await createFlowsFlowIdPublishWithRequestBuilder(flowId: flowId, token: token, wabaAccountId: wabaAccountId).execute().body
    }

    /**
     Publish Flow
     - POST /flows/{flowId}/publish
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter flowId: (path) Flow ID 
     - parameter token: (query) JWT token or API key for authorization 
     - parameter wabaAccountId: (query)  (optional)
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func createFlowsFlowIdPublishWithRequestBuilder(flowId: String, token: String, wabaAccountId: String? = nil) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/flows/{flowId}/publish"
        let flowIdPreEscape = "\(APIHelper.mapValueToPathItem(flowId))"
        let flowIdPostEscape = flowIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{flowId}", with: flowIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
            "wabaAccountId": (wrappedValue: wabaAccountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete Flow
     
     - parameter flowId: (path) Flow ID 
     - parameter token: (query) JWT token or API key for authorization 
     - parameter wabaAccountId: (query)  (optional)
     - returns: DeleteFlowsFlowId200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteFlowsFlowId(flowId: String, token: String, wabaAccountId: String? = nil) async throws -> DeleteFlowsFlowId200Response {
        return try await deleteFlowsFlowIdWithRequestBuilder(flowId: flowId, token: token, wabaAccountId: wabaAccountId).execute().body
    }

    /**
     Delete Flow
     - DELETE /flows/{flowId}
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter flowId: (path) Flow ID 
     - parameter token: (query) JWT token or API key for authorization 
     - parameter wabaAccountId: (query)  (optional)
     - returns: RequestBuilder<DeleteFlowsFlowId200Response> 
     */
    open class func deleteFlowsFlowIdWithRequestBuilder(flowId: String, token: String, wabaAccountId: String? = nil) -> RequestBuilder<DeleteFlowsFlowId200Response> {
        var localVariablePath = "/flows/{flowId}"
        let flowIdPreEscape = "\(APIHelper.mapValueToPathItem(flowId))"
        let flowIdPostEscape = flowIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{flowId}", with: flowIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
            "wabaAccountId": (wrappedValue: wabaAccountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeleteFlowsFlowId200Response>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Flow Details
     
     - parameter flowId: (path) Flow ID 
     - parameter token: (query) JWT token or API key for authorization 
     - parameter wabaAccountId: (query)  (optional)
     - returns: CreateGroups200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getFlowsFlowId(flowId: String, token: String, wabaAccountId: String? = nil) async throws -> CreateGroups200Response {
        return try await getFlowsFlowIdWithRequestBuilder(flowId: flowId, token: token, wabaAccountId: wabaAccountId).execute().body
    }

    /**
     Get Flow Details
     - GET /flows/{flowId}
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter flowId: (path) Flow ID 
     - parameter token: (query) JWT token or API key for authorization 
     - parameter wabaAccountId: (query)  (optional)
     - returns: RequestBuilder<CreateGroups200Response> 
     */
    open class func getFlowsFlowIdWithRequestBuilder(flowId: String, token: String, wabaAccountId: String? = nil) -> RequestBuilder<CreateGroups200Response> {
        var localVariablePath = "/flows/{flowId}"
        let flowIdPreEscape = "\(APIHelper.mapValueToPathItem(flowId))"
        let flowIdPostEscape = flowIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{flowId}", with: flowIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
            "wabaAccountId": (wrappedValue: wabaAccountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateGroups200Response>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Preview Flow
     
     - parameter flowId: (path) Flow ID 
     - parameter token: (query) JWT token or API key for authorization 
     - parameter wabaAccountId: (query)  (optional)
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getFlowsFlowIdPreview(flowId: String, token: String, wabaAccountId: String? = nil) async throws -> [String: AnyCodable] {
        return try await getFlowsFlowIdPreviewWithRequestBuilder(flowId: flowId, token: token, wabaAccountId: wabaAccountId).execute().body
    }

    /**
     Preview Flow
     - GET /flows/{flowId}/preview
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter flowId: (path) Flow ID 
     - parameter token: (query) JWT token or API key for authorization 
     - parameter wabaAccountId: (query)  (optional)
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func getFlowsFlowIdPreviewWithRequestBuilder(flowId: String, token: String, wabaAccountId: String? = nil) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/flows/{flowId}/preview"
        let flowIdPreEscape = "\(APIHelper.mapValueToPathItem(flowId))"
        let flowIdPostEscape = flowIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{flowId}", with: flowIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
            "wabaAccountId": (wrappedValue: wabaAccountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get business encryption public key
     
     - parameter token: (query) JWT token or API key for authorization 
     - returns: GetWhatsappBusinessEncryption200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getWhatsappBusinessEncryption(token: String) async throws -> GetWhatsappBusinessEncryption200Response {
        return try await getWhatsappBusinessEncryptionWithRequestBuilder(token: token).execute().body
    }

    /**
     Get business encryption public key
     - GET /whatsapp_business_encryption
     - Retrieve the WhatsApp business public key and signature status for this channel's phone number. Required before publishing or sending Flows that use data encryption. 
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - returns: RequestBuilder<GetWhatsappBusinessEncryption200Response> 
     */
    open class func getWhatsappBusinessEncryptionWithRequestBuilder(token: String) -> RequestBuilder<GetWhatsappBusinessEncryption200Response> {
        let localVariablePath = "/whatsapp_business_encryption"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetWhatsappBusinessEncryption200Response>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List Flows
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter wabaAccountId: (query)  (optional)
     - returns: ListFlows200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listFlows(token: String, wabaAccountId: String? = nil) async throws -> ListFlows200Response {
        return try await listFlowsWithRequestBuilder(token: token, wabaAccountId: wabaAccountId).execute().body
    }

    /**
     List Flows
     - GET /flows
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter wabaAccountId: (query)  (optional)
     - returns: RequestBuilder<ListFlows200Response> 
     */
    open class func listFlowsWithRequestBuilder(token: String, wabaAccountId: String? = nil) -> RequestBuilder<ListFlows200Response> {
        let localVariablePath = "/flows"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
            "wabaAccountId": (wrappedValue: wabaAccountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListFlows200Response>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update Flow Structure
     
     - parameter flowId: (path) Flow ID 
     - parameter token: (query) JWT token or API key for authorization 
     - parameter wabaAccountId: (query)  (optional)
     - returns: PatchFlowsFlowIdAssets200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func patchFlowsFlowIdAssets(flowId: String, token: String, wabaAccountId: String? = nil) async throws -> PatchFlowsFlowIdAssets200Response {
        return try await patchFlowsFlowIdAssetsWithRequestBuilder(flowId: flowId, token: token, wabaAccountId: wabaAccountId).execute().body
    }

    /**
     Update Flow Structure
     - PATCH /flows/{flowId}/assets
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter flowId: (path) Flow ID 
     - parameter token: (query) JWT token or API key for authorization 
     - parameter wabaAccountId: (query)  (optional)
     - returns: RequestBuilder<PatchFlowsFlowIdAssets200Response> 
     */
    open class func patchFlowsFlowIdAssetsWithRequestBuilder(flowId: String, token: String, wabaAccountId: String? = nil) -> RequestBuilder<PatchFlowsFlowIdAssets200Response> {
        var localVariablePath = "/flows/{flowId}/assets"
        let flowIdPreEscape = "\(APIHelper.mapValueToPathItem(flowId))"
        let flowIdPostEscape = flowIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{flowId}", with: flowIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
            "wabaAccountId": (wrappedValue: wabaAccountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PatchFlowsFlowIdAssets200Response>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update Flow Metadata
     
     - parameter flowId: (path) Flow ID 
     - parameter token: (query) JWT token or API key for authorization 
     - parameter wabaAccountId: (query)  (optional)
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func patchFlowsFlowIdMetadata(flowId: String, token: String, wabaAccountId: String? = nil) async throws -> [String: AnyCodable] {
        return try await patchFlowsFlowIdMetadataWithRequestBuilder(flowId: flowId, token: token, wabaAccountId: wabaAccountId).execute().body
    }

    /**
     Update Flow Metadata
     - PATCH /flows/{flowId}/metadata
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter flowId: (path) Flow ID 
     - parameter token: (query) JWT token or API key for authorization 
     - parameter wabaAccountId: (query)  (optional)
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func patchFlowsFlowIdMetadataWithRequestBuilder(flowId: String, token: String, wabaAccountId: String? = nil) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/flows/{flowId}/metadata"
        let flowIdPreEscape = "\(APIHelper.mapValueToPathItem(flowId))"
        let flowIdPostEscape = flowIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{flowId}", with: flowIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
            "wabaAccountId": (wrappedValue: wabaAccountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Set business encryption public key
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter setWhatsappBusinessEncryptionRequest: (body)  
     - returns: CreateCommerce200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func setWhatsappBusinessEncryption(token: String, setWhatsappBusinessEncryptionRequest: SetWhatsappBusinessEncryptionRequest) async throws -> CreateCommerce200Response {
        return try await setWhatsappBusinessEncryptionWithRequestBuilder(token: token, setWhatsappBusinessEncryptionRequest: setWhatsappBusinessEncryptionRequest).execute().body
    }

    /**
     Set business encryption public key
     - POST /whatsapp_business_encryption
     - Upload and sign a 2048-bit RSA business public key (PEM) for this channel's phone number. Meta requires a signed key before Flow publish/send. Only one active key per number; a new upload replaces the previous key. 
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter setWhatsappBusinessEncryptionRequest: (body)  
     - returns: RequestBuilder<CreateCommerce200Response> 
     */
    open class func setWhatsappBusinessEncryptionWithRequestBuilder(token: String, setWhatsappBusinessEncryptionRequest: SetWhatsappBusinessEncryptionRequest) -> RequestBuilder<CreateCommerce200Response> {
        let localVariablePath = "/whatsapp_business_encryption"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: setWhatsappBusinessEncryptionRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateCommerce200Response>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
