//
// MessagingAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class MessagingAPI {

    /**
     Mark message as read
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter messageId: (form)  (optional)
     - parameter msgId: (form)  (optional)
     - parameter typingIndicator: (form) Show WhatsApp typing indicator (max 25s or until reply) (optional, default to false)
     - returns: CreateReadMessage200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createReadMessage(token: String, messageId: String? = nil, msgId: String? = nil, typingIndicator: Bool? = nil) async throws -> CreateReadMessage200Response {
        return try await createReadMessageWithRequestBuilder(token: token, messageId: messageId, msgId: msgId, typingIndicator: typingIndicator).execute().body
    }

    /**
     Mark message as read
     - POST /readMessage
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter messageId: (form)  (optional)
     - parameter msgId: (form)  (optional)
     - parameter typingIndicator: (form) Show WhatsApp typing indicator (max 25s or until reply) (optional, default to false)
     - returns: RequestBuilder<CreateReadMessage200Response> 
     */
    open class func createReadMessageWithRequestBuilder(token: String, messageId: String? = nil, msgId: String? = nil, typingIndicator: Bool? = nil) -> RequestBuilder<CreateReadMessage200Response> {
        let localVariablePath = "/readMessage"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "messageId": messageId?.encodeToJSON(),
            "msgId": msgId?.encodeToJSON(),
            "typingIndicator": typingIndicator?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateReadMessage200Response>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Upload media
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter requestBody: (body)  (optional)
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createUploadMedia(token: String, requestBody: [String: AnyCodable]? = nil) async throws {
        return try await createUploadMediaWithRequestBuilder(token: token, requestBody: requestBody).execute().body
    }

    /**
     Upload media
     - POST /uploadMedia
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter requestBody: (body)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func createUploadMediaWithRequestBuilder(token: String, requestBody: [String: AnyCodable]? = nil) -> RequestBuilder<Void> {
        let localVariablePath = "/uploadMedia"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestBody)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = OneMsgSdkAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete media from WABA storage
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter mediaId: (path) Numeric WABA media id 
     - returns: SuccessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteMedia(token: String, mediaId: String) async throws -> SuccessResponse {
        return try await deleteMediaWithRequestBuilder(token: token, mediaId: mediaId).execute().body
    }

    /**
     Delete media from WABA storage
     - DELETE /media/{mediaId}
     - Delete previously uploaded media by numeric `mediaId` (from `/uploadMedia`).  This is the canonical deletion endpoint and uses the REST `DELETE` verb on the media resource path. The older `POST /deleteMedia` is a deprecated alias. 
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter mediaId: (path) Numeric WABA media id 
     - returns: RequestBuilder<SuccessResponse> 
     */
    open class func deleteMediaWithRequestBuilder(token: String, mediaId: String) -> RequestBuilder<SuccessResponse> {
        var localVariablePath = "/media/{mediaId}"
        let mediaIdPreEscape = "\(APIHelper.mapValueToPathItem(mediaId))"
        let mediaIdPostEscape = mediaIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{mediaId}", with: mediaIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponse>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete media from WABA storage (deprecated alias)
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter deleteMediaLegacyRequest: (body)  
     - returns: SuccessResponse
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteMediaLegacy(token: String, deleteMediaLegacyRequest: DeleteMediaLegacyRequest) async throws -> SuccessResponse {
        return try await deleteMediaLegacyWithRequestBuilder(token: token, deleteMediaLegacyRequest: deleteMediaLegacyRequest).execute().body
    }

    /**
     Delete media from WABA storage (deprecated alias)
     - POST /deleteMedia
     - **Deprecated.** Use `DELETE /media/{mediaId}` instead.  This POST alias is kept for backward compatibility with earlier integrations. New integrations should call `DELETE /media/{mediaId}`: 1msg follows REST conventions for resource deletion going forward (delete a resource with the `DELETE` verb on its resource path). 
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter deleteMediaLegacyRequest: (body)  
     - returns: RequestBuilder<SuccessResponse> 
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    open class func deleteMediaLegacyWithRequestBuilder(token: String, deleteMediaLegacyRequest: DeleteMediaLegacyRequest) -> RequestBuilder<SuccessResponse> {
        let localVariablePath = "/deleteMedia"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: deleteMediaLegacyRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponse>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get MM Lite availability and status
     
     - parameter token: (query) JWT token or API key for authorization 
     - returns: GetMmLiteStatus200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getMmLiteStatus(token: String) async throws -> GetMmLiteStatus200Response {
        return try await getMmLiteStatusWithRequestBuilder(token: token).execute().body
    }

    /**
     Get MM Lite availability and status
     - GET /mmLiteStatus
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - returns: RequestBuilder<GetMmLiteStatus200Response> 
     */
    open class func getMmLiteStatusWithRequestBuilder(token: String) -> RequestBuilder<GetMmLiteStatus200Response> {
        let localVariablePath = "/mmLiteStatus"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetMmLiteStatus200Response>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get messages list
     
     - parameter token: (query) JWT token or API key for authorization 
     - returns: ListMessages200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listMessages(token: String) async throws -> ListMessages200Response {
        return try await listMessagesWithRequestBuilder(token: token).execute().body
    }

    /**
     Get messages list
     - GET /messages
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - returns: RequestBuilder<ListMessages200Response> 
     */
    open class func listMessagesWithRequestBuilder(token: String) -> RequestBuilder<ListMessages200Response> {
        let localVariablePath = "/messages"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListMessages200Response>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Retrieve uploaded media metadata
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter mediaId: (query)  
     - returns: RetrieveMedia200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func retrieveMedia(token: String, mediaId: String) async throws -> RetrieveMedia200Response {
        return try await retrieveMediaWithRequestBuilder(token: token, mediaId: mediaId).execute().body
    }

    /**
     Retrieve uploaded media metadata
     - GET /retrieveMedia
     - Get WABA media URL and metadata by mediaId (from uploadMedia). The returned `url` is temporary and typically expires within ~5 minutes. 
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter mediaId: (query)  
     - returns: RequestBuilder<RetrieveMedia200Response> 
     */
    open class func retrieveMediaWithRequestBuilder(token: String, mediaId: String) -> RequestBuilder<RetrieveMedia200Response> {
        let localVariablePath = "/retrieveMedia"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
            "mediaId": (wrappedValue: mediaId.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RetrieveMedia200Response>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Send address request message
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendAddressMessageRequest: (body)  
     - returns: MessageSentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func sendAddressMessage(token: String, sendAddressMessageRequest: SendAddressMessageRequest) async throws -> MessageSentResponse {
        return try await sendAddressMessageWithRequestBuilder(token: token, sendAddressMessageRequest: sendAddressMessageRequest).execute().body
    }

    /**
     Send address request message
     - POST /sendAddressMessage
     - Request shipping address from the user (WhatsApp interactive `address_message`).  **India and Singapore only.** Requires: - Business WhatsApp number registered in that country - Recipient phone matching the country (`+91` ↔ `IN`, `+65` ↔ `SG`)  Pass `country: \"IN\"` or `country: \"SG\"`. Eligibility is validated upstream; mismatches (e.g. Singapore phone with `country: \"IN\"`) return errors such as `Unsupported Interactive Message type` (HTTP 200 with `sent: false`).  Optional action parameters: `values`, `saved_addresses`, `validation_errors`. 
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendAddressMessageRequest: (body)  
     - returns: RequestBuilder<MessageSentResponse> 
     */
    open class func sendAddressMessageWithRequestBuilder(token: String, sendAddressMessageRequest: SendAddressMessageRequest) -> RequestBuilder<MessageSentResponse> {
        let localVariablePath = "/sendAddressMessage"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sendAddressMessageRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageSentResponse>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Send Reply Buttons Message
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendButtonRequest: (body)  (optional)
     - returns: MessageSentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func sendButton(token: String, sendButtonRequest: SendButtonRequest? = nil) async throws -> MessageSentResponse {
        return try await sendButtonWithRequestBuilder(token: token, sendButtonRequest: sendButtonRequest).execute().body
    }

    /**
     Send Reply Buttons Message
     - POST /sendButton
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendButtonRequest: (body)  (optional)
     - returns: RequestBuilder<MessageSentResponse> 
     */
    open class func sendButtonWithRequestBuilder(token: String, sendButtonRequest: SendButtonRequest? = nil) -> RequestBuilder<MessageSentResponse> {
        let localVariablePath = "/sendButton"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sendButtonRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageSentResponse>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Send Carousel
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter params: (form) Required. Template-like structure (same as sendTemplate params). Must include a CAROUSEL component and its cards.  Structure: - params[] item with type CAROUSEL and cards (2..10) - cards[] item:   - components[] items:     - header: parameters[0] with type image/video/product       - image: {\\\&quot;image\\\&quot;: {\\\&quot;link\\\&quot;: \\\&quot;https://...\\\&quot;}}       - video: {\\\&quot;video\\\&quot;: {\\\&quot;link\\\&quot;: \\\&quot;https://...\\\&quot;}}       - product: {\\\&quot;product\\\&quot;: {\\\&quot;catalog_id\\\&quot;: \\\&quot;...\\\&quot;, \\\&quot;product_retailer_id\\\&quot;: \\\&quot;...\\\&quot;}}     - button: sub_type url or quick_reply       - url: parameters {\\\&quot;text\\\&quot;: \\\&quot;Button\\\&quot;, \\\&quot;url\\\&quot;: \\\&quot;https://...\\\&quot;}       - quick_reply: parameters[] of {\\\&quot;id\\\&quot;: \\\&quot;...\\\&quot;, \\\&quot;text\\\&quot;: \\\&quot;...\\\&quot;}  
     - parameter body: (form) Text shown above the carousel. Optional. If omitted and params include a body component, the body will be taken from params. (optional)
     - parameter quotedMsgId: (form) Quoted message ID (Cloud API) (optional)
     - parameter chatId: (form) Required if phone is not set. Chat ID from the message list. Examples: 12020721369@c.us or 120363046942338209@g.us(group) (optional)
     - parameter phone: (form) Required if chatId is not set. A phone number starting with the country code. USA example: 12020721369. (optional)
     - returns: MessageSentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func sendCarousel(token: String, params: [AnyCodable], body: String? = nil, quotedMsgId: String? = nil, chatId: String? = nil, phone: Int? = nil) async throws -> MessageSentResponse {
        return try await sendCarouselWithRequestBuilder(token: token, params: params, body: body, quotedMsgId: quotedMsgId, chatId: chatId, phone: phone).execute().body
    }

    /**
     Send Carousel
     - POST /sendCarousel
     - You can send product cards via Carousel in two ways:  Template messages: do not require a 24-hour customer service window between you and the recipient. Use sendTemplate.  Free-form messages: can be sent only when a customer service window is open between you and the recipient. Use sendCarousel.  The message structure in /sendCarousel is largely similar to sending a template. However, in this case you must  explicitly specify all elements that are created in advance when working with templates. This is because the message  is sent without using a template.  In /sendCarousel, for sending a Catalog Carousel there can be either 1 URL button or one or more quick reply buttons. 
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter params: (form) Required. Template-like structure (same as sendTemplate params). Must include a CAROUSEL component and its cards.  Structure: - params[] item with type CAROUSEL and cards (2..10) - cards[] item:   - components[] items:     - header: parameters[0] with type image/video/product       - image: {\\\&quot;image\\\&quot;: {\\\&quot;link\\\&quot;: \\\&quot;https://...\\\&quot;}}       - video: {\\\&quot;video\\\&quot;: {\\\&quot;link\\\&quot;: \\\&quot;https://...\\\&quot;}}       - product: {\\\&quot;product\\\&quot;: {\\\&quot;catalog_id\\\&quot;: \\\&quot;...\\\&quot;, \\\&quot;product_retailer_id\\\&quot;: \\\&quot;...\\\&quot;}}     - button: sub_type url or quick_reply       - url: parameters {\\\&quot;text\\\&quot;: \\\&quot;Button\\\&quot;, \\\&quot;url\\\&quot;: \\\&quot;https://...\\\&quot;}       - quick_reply: parameters[] of {\\\&quot;id\\\&quot;: \\\&quot;...\\\&quot;, \\\&quot;text\\\&quot;: \\\&quot;...\\\&quot;}  
     - parameter body: (form) Text shown above the carousel. Optional. If omitted and params include a body component, the body will be taken from params. (optional)
     - parameter quotedMsgId: (form) Quoted message ID (Cloud API) (optional)
     - parameter chatId: (form) Required if phone is not set. Chat ID from the message list. Examples: 12020721369@c.us or 120363046942338209@g.us(group) (optional)
     - parameter phone: (form) Required if chatId is not set. A phone number starting with the country code. USA example: 12020721369. (optional)
     - returns: RequestBuilder<MessageSentResponse> 
     */
    open class func sendCarouselWithRequestBuilder(token: String, params: [AnyCodable], body: String? = nil, quotedMsgId: String? = nil, chatId: String? = nil, phone: Int? = nil) -> RequestBuilder<MessageSentResponse> {
        let localVariablePath = "/sendCarousel"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "body": body?.encodeToJSON(),
            "params": params.encodeToJSON(),
            "quotedMsgId": quotedMsgId?.encodeToJSON(),
            "chatId": chatId?.encodeToJSON(),
            "phone": phone?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageSentResponse>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Send a Contact
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendContactRequest: (body)  (optional)
     - returns: MessageSentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func sendContact(token: String, sendContactRequest: SendContactRequest? = nil) async throws -> MessageSentResponse {
        return try await sendContactWithRequestBuilder(token: token, sendContactRequest: sendContactRequest).execute().body
    }

    /**
     Send a Contact
     - POST /sendContact
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendContactRequest: (body)  (optional)
     - returns: RequestBuilder<MessageSentResponse> 
     */
    open class func sendContactWithRequestBuilder(token: String, sendContactRequest: SendContactRequest? = nil) -> RequestBuilder<MessageSentResponse> {
        let localVariablePath = "/sendContact"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sendContactRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageSentResponse>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Send CTA URL interactive message
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendCtaUrlRequest: (body)  
     - returns: MessageSentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func sendCtaUrl(token: String, sendCtaUrlRequest: SendCtaUrlRequest) async throws -> MessageSentResponse {
        return try await sendCtaUrlWithRequestBuilder(token: token, sendCtaUrlRequest: sendCtaUrlRequest).execute().body
    }

    /**
     Send CTA URL interactive message
     - POST /sendCtaUrl
     - Send an interactive message with a single call-to-action URL button.
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendCtaUrlRequest: (body)  
     - returns: RequestBuilder<MessageSentResponse> 
     */
    open class func sendCtaUrlWithRequestBuilder(token: String, sendCtaUrlRequest: SendCtaUrlRequest) -> RequestBuilder<MessageSentResponse> {
        let localVariablePath = "/sendCtaUrl"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sendCtaUrlRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageSentResponse>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter mediaType
     */
    public enum MediaType_sendFile: String, CaseIterable {
        case image = "image"
        case video = "video"
        case audio = "audio"
        case document = "document"
    }

    /**
     Send a File
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter body: (form) File source (required unless mediaId is set): - HTTP/HTTPS URL - Base64 data URI  (optional)
     - parameter filename: (form) File name with extension (required with body, not with mediaId) (optional)
     - parameter mediaId: (form) WABA media id from uploadMedia (alternative to body) (optional)
     - parameter mediaType: (form) Required when using mediaId (optional)
     - parameter voice: (form) Native WhatsApp voice note (audio/ogg only) (optional)
     - parameter caption: (form)  (optional)
     - parameter quotedMsgId: (form)  (optional)
     - parameter chatId: (form)  (optional)
     - parameter phone: (form)  (optional)
     - returns: MessageSentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func sendFile(token: String, body: String? = nil, filename: String? = nil, mediaId: String? = nil, mediaType: MediaType_sendFile? = nil, voice: Bool? = nil, caption: String? = nil, quotedMsgId: String? = nil, chatId: String? = nil, phone: Int? = nil) async throws -> MessageSentResponse {
        return try await sendFileWithRequestBuilder(token: token, body: body, filename: filename, mediaId: mediaId, mediaType: mediaType, voice: voice, caption: caption, quotedMsgId: quotedMsgId, chatId: chatId, phone: phone).execute().body
    }

    /**
     Send a File
     - POST /sendFile
     - Send a file to an existing chat. (Only if the dialogue has an Open Session).  Only one of two parameters is needed to determine the destination - chatId or phone. 
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter body: (form) File source (required unless mediaId is set): - HTTP/HTTPS URL - Base64 data URI  (optional)
     - parameter filename: (form) File name with extension (required with body, not with mediaId) (optional)
     - parameter mediaId: (form) WABA media id from uploadMedia (alternative to body) (optional)
     - parameter mediaType: (form) Required when using mediaId (optional)
     - parameter voice: (form) Native WhatsApp voice note (audio/ogg only) (optional)
     - parameter caption: (form)  (optional)
     - parameter quotedMsgId: (form)  (optional)
     - parameter chatId: (form)  (optional)
     - parameter phone: (form)  (optional)
     - returns: RequestBuilder<MessageSentResponse> 
     */
    open class func sendFileWithRequestBuilder(token: String, body: String? = nil, filename: String? = nil, mediaId: String? = nil, mediaType: MediaType_sendFile? = nil, voice: Bool? = nil, caption: String? = nil, quotedMsgId: String? = nil, chatId: String? = nil, phone: Int? = nil) -> RequestBuilder<MessageSentResponse> {
        let localVariablePath = "/sendFile"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "body": body?.encodeToJSON(),
            "filename": filename?.encodeToJSON(),
            "mediaId": mediaId?.encodeToJSON(),
            "mediaType": mediaType?.encodeToJSON(),
            "voice": voice?.encodeToJSON(),
            "caption": caption?.encodeToJSON(),
            "quotedMsgId": quotedMsgId?.encodeToJSON(),
            "chatId": chatId?.encodeToJSON(),
            "phone": phone?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageSentResponse>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter flowAction
     */
    public enum FlowAction_sendFlow: String, CaseIterable {
        case navigate = "navigate"
        case dataExchange = "data_exchange"
    }

    /**
     * enum for parameter mode
     */
    public enum Mode_sendFlow: String, CaseIterable {
        case draft = "draft"
        case published = "published"
    }

    /**
     Send WhatsApp Flow Message
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter body: (form) Flow message body text 
     - parameter flowId: (form) Published Flow ID 
     - parameter flowToken: (form) Flow token generated by the business 
     - parameter flowCta: (form) CTA button text 
     - parameter header: (form)  (optional)
     - parameter footer: (form) Footer text (optional)
     - parameter flowAction: (form) Flow action type (optional)
     - parameter flowActionPayload: (form) Required for flowAction&#x3D;navigate (screen is required). Ignored for data_exchange. If data is provided, it must be a non-empty object. (optional)
     - parameter flowMessageVersion: (form) Flow message version (default \\\&quot;3\\\&quot;) (optional)
     - parameter mode: (form) Flow mode (draft or published). If omitted, provider default applies (optional)
     - parameter flowActionData: (form) Shortcut for flowActionPayload.data (optional) (optional)
     - parameter flowActionScreen: (form) Shortcut for flowActionPayload.screen (optional) (optional)
     - parameter quotedMsgId: (form) Quoted message ID (Cloud API) (optional)
     - parameter chatId: (form) Required if phone is not set. Chat ID from the message list. Examples: 12020721369@c.us or 120363046942338209@g.us(group) (optional)
     - parameter phone: (form) Required if chatId is not set. A phone number starting with the country code. USA example: 12020721369. (optional)
     - returns: MessageSentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func sendFlow(token: String, body: String, flowId: String, flowToken: String, flowCta: String, header: SendFlowRequestHeader? = nil, footer: String? = nil, flowAction: FlowAction_sendFlow? = nil, flowActionPayload: AnyCodable? = nil, flowMessageVersion: String? = nil, mode: Mode_sendFlow? = nil, flowActionData: AnyCodable? = nil, flowActionScreen: String? = nil, quotedMsgId: String? = nil, chatId: String? = nil, phone: Int? = nil) async throws -> MessageSentResponse {
        return try await sendFlowWithRequestBuilder(token: token, body: body, flowId: flowId, flowToken: flowToken, flowCta: flowCta, header: header, footer: footer, flowAction: flowAction, flowActionPayload: flowActionPayload, flowMessageVersion: flowMessageVersion, mode: mode, flowActionData: flowActionData, flowActionScreen: flowActionScreen, quotedMsgId: quotedMsgId, chatId: chatId, phone: phone).execute().body
    }

    /**
     Send WhatsApp Flow Message
     - POST /sendFlow
     - Send Interactive WhatsApp Flow message to an existing chat. (Only if the dialogue has an Open Session).  Only one of two parameters is needed to determine the destination - chatId or phone.  Use this method to send a published WhatsApp Flow as a service (interactive) message.  If the 24-hour window is closed, send a template with a FLOW button via /sendTemplate. 
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter body: (form) Flow message body text 
     - parameter flowId: (form) Published Flow ID 
     - parameter flowToken: (form) Flow token generated by the business 
     - parameter flowCta: (form) CTA button text 
     - parameter header: (form)  (optional)
     - parameter footer: (form) Footer text (optional)
     - parameter flowAction: (form) Flow action type (optional)
     - parameter flowActionPayload: (form) Required for flowAction&#x3D;navigate (screen is required). Ignored for data_exchange. If data is provided, it must be a non-empty object. (optional)
     - parameter flowMessageVersion: (form) Flow message version (default \\\&quot;3\\\&quot;) (optional)
     - parameter mode: (form) Flow mode (draft or published). If omitted, provider default applies (optional)
     - parameter flowActionData: (form) Shortcut for flowActionPayload.data (optional) (optional)
     - parameter flowActionScreen: (form) Shortcut for flowActionPayload.screen (optional) (optional)
     - parameter quotedMsgId: (form) Quoted message ID (Cloud API) (optional)
     - parameter chatId: (form) Required if phone is not set. Chat ID from the message list. Examples: 12020721369@c.us or 120363046942338209@g.us(group) (optional)
     - parameter phone: (form) Required if chatId is not set. A phone number starting with the country code. USA example: 12020721369. (optional)
     - returns: RequestBuilder<MessageSentResponse> 
     */
    open class func sendFlowWithRequestBuilder(token: String, body: String, flowId: String, flowToken: String, flowCta: String, header: SendFlowRequestHeader? = nil, footer: String? = nil, flowAction: FlowAction_sendFlow? = nil, flowActionPayload: AnyCodable? = nil, flowMessageVersion: String? = nil, mode: Mode_sendFlow? = nil, flowActionData: AnyCodable? = nil, flowActionScreen: String? = nil, quotedMsgId: String? = nil, chatId: String? = nil, phone: Int? = nil) -> RequestBuilder<MessageSentResponse> {
        let localVariablePath = "/sendFlow"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "body": body.encodeToJSON(),
            "header": header?.encodeToJSON(),
            "footer": footer?.encodeToJSON(),
            "flowId": flowId.encodeToJSON(),
            "flowToken": flowToken.encodeToJSON(),
            "flowCta": flowCta.encodeToJSON(),
            "flowAction": flowAction?.encodeToJSON(),
            "flowActionPayload": flowActionPayload?.encodeToJSON(),
            "flowMessageVersion": flowMessageVersion?.encodeToJSON(),
            "mode": mode?.encodeToJSON(),
            "flowActionData": flowActionData?.encodeToJSON(),
            "flowActionScreen": flowActionScreen?.encodeToJSON(),
            "quotedMsgId": quotedMsgId?.encodeToJSON(),
            "chatId": chatId?.encodeToJSON(),
            "phone": phone?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageSentResponse>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Send List Message
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendListRequest: (body)  (optional)
     - returns: MessageSentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func sendList(token: String, sendListRequest: SendListRequest? = nil) async throws -> MessageSentResponse {
        return try await sendListWithRequestBuilder(token: token, sendListRequest: sendListRequest).execute().body
    }

    /**
     Send List Message
     - POST /sendList
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendListRequest: (body)  (optional)
     - returns: RequestBuilder<MessageSentResponse> 
     */
    open class func sendListWithRequestBuilder(token: String, sendListRequest: SendListRequest? = nil) -> RequestBuilder<MessageSentResponse> {
        let localVariablePath = "/sendList"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sendListRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageSentResponse>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Send a Location
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter lat: (form) Latitude of the location. Example: 45.018337 
     - parameter lng: (form) Longitude of the location. Example: -73.968285 
     - parameter address: (form) Address of the location. Only displayed if name is present. Example: 9766 Valley View St., New York, NY 10024 (optional)
     - parameter name: (form) Name of the location. Example: Facebook HQ (optional)
     - parameter quotedMsgId: (form) Quoted message ID (Cloud API) (optional)
     - parameter chatId: (form) Required if phone is not set. Chat ID from the message list. Examples: 12020721369@c.us or 120363046942338209@g.us(group) (optional)
     - parameter phone: (form) Required if chatId is not set. A phone number starting with the country code. USA example: 12020721369. (optional)
     - returns: MessageSentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func sendLocation(token: String, lat: String, lng: String, address: String? = nil, name: String? = nil, quotedMsgId: String? = nil, chatId: String? = nil, phone: Int? = nil) async throws -> MessageSentResponse {
        return try await sendLocationWithRequestBuilder(token: token, lat: lat, lng: lng, address: address, name: name, quotedMsgId: quotedMsgId, chatId: chatId, phone: phone).execute().body
    }

    /**
     Send a Location
     - POST /sendLocation
     - Send a location to an existing chat. (Only if the dialogue has an Open Session).  Only one of two parameters is needed to determine the destination - chatId or phone. 
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter lat: (form) Latitude of the location. Example: 45.018337 
     - parameter lng: (form) Longitude of the location. Example: -73.968285 
     - parameter address: (form) Address of the location. Only displayed if name is present. Example: 9766 Valley View St., New York, NY 10024 (optional)
     - parameter name: (form) Name of the location. Example: Facebook HQ (optional)
     - parameter quotedMsgId: (form) Quoted message ID (Cloud API) (optional)
     - parameter chatId: (form) Required if phone is not set. Chat ID from the message list. Examples: 12020721369@c.us or 120363046942338209@g.us(group) (optional)
     - parameter phone: (form) Required if chatId is not set. A phone number starting with the country code. USA example: 12020721369. (optional)
     - returns: RequestBuilder<MessageSentResponse> 
     */
    open class func sendLocationWithRequestBuilder(token: String, lat: String, lng: String, address: String? = nil, name: String? = nil, quotedMsgId: String? = nil, chatId: String? = nil, phone: Int? = nil) -> RequestBuilder<MessageSentResponse> {
        let localVariablePath = "/sendLocation"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "lat": lat.encodeToJSON(),
            "lng": lng.encodeToJSON(),
            "address": address?.encodeToJSON(),
            "name": name?.encodeToJSON(),
            "quotedMsgId": quotedMsgId?.encodeToJSON(),
            "chatId": chatId?.encodeToJSON(),
            "phone": phone?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageSentResponse>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Send Location Request Message
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendLocationRequestRequest: (body)  (optional)
     - returns: MessageSentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func sendLocationRequest(token: String, sendLocationRequestRequest: SendLocationRequestRequest? = nil) async throws -> MessageSentResponse {
        return try await sendLocationRequestWithRequestBuilder(token: token, sendLocationRequestRequest: sendLocationRequestRequest).execute().body
    }

    /**
     Send Location Request Message
     - POST /sendLocationRequest
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendLocationRequestRequest: (body)  (optional)
     - returns: RequestBuilder<MessageSentResponse> 
     */
    open class func sendLocationRequestWithRequestBuilder(token: String, sendLocationRequestRequest: SendLocationRequestRequest? = nil) -> RequestBuilder<MessageSentResponse> {
        let localVariablePath = "/sendLocationRequest"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sendLocationRequestRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageSentResponse>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Send a Message
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter body: (form) Message text, UTF-8 or UTF-16 string with emoji 
     - parameter quotedMsgId: (form) Message ID to quote/reply to (Cloud API wamid) (optional)
     - parameter chatId: (form) Chat ID in format: phone@c.us (individual) or phone@g.us (group) (optional)
     - parameter phone: (form) Phone number starting with country code (alternative to chatId) (optional)
     - returns: MessageSentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func sendMessage(token: String, body: String, quotedMsgId: String? = nil, chatId: String? = nil, phone: Int? = nil) async throws -> MessageSentResponse {
        return try await sendMessageWithRequestBuilder(token: token, body: body, quotedMsgId: quotedMsgId, chatId: chatId, phone: phone).execute().body
    }

    /**
     Send a Message
     - POST /sendMessage
     - Send a message to an existing chat. (Only if the dialogue has an Open Session).  The message will be added to the queue for sending and delivered even if the phone  is disconnected from the Internet or authorization is not passed.  Only one of two parameters is needed to determine the destination - chatId or phone. 
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter body: (form) Message text, UTF-8 or UTF-16 string with emoji 
     - parameter quotedMsgId: (form) Message ID to quote/reply to (Cloud API wamid) (optional)
     - parameter chatId: (form) Chat ID in format: phone@c.us (individual) or phone@g.us (group) (optional)
     - parameter phone: (form) Phone number starting with country code (alternative to chatId) (optional)
     - returns: RequestBuilder<MessageSentResponse> 
     */
    open class func sendMessageWithRequestBuilder(token: String, body: String, quotedMsgId: String? = nil, chatId: String? = nil, phone: Int? = nil) -> RequestBuilder<MessageSentResponse> {
        let localVariablePath = "/sendMessage"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "body": body.encodeToJSON(),
            "quotedMsgId": quotedMsgId?.encodeToJSON(),
            "chatId": chatId?.encodeToJSON(),
            "phone": phone?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageSentResponse>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Send order details (India payments template)
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendOrderDetailsRequest: (body)  
     - returns: MessageSentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func sendOrderDetails(token: String, sendOrderDetailsRequest: SendOrderDetailsRequest) async throws -> MessageSentResponse {
        return try await sendOrderDetailsWithRequestBuilder(token: token, sendOrderDetailsRequest: sendOrderDetailsRequest).execute().body
    }

    /**
     Send order details (India payments template)
     - POST /sendOrderDetails
     - Send a WhatsApp **order details** payment / invoice message using a pre-approved **Utility** template that has an `ORDER_DETAILS` button.  **India only** (WhatsApp Payments India). Requires: - India WhatsApp Business number - Commerce enabled on the channel (`GET`/`POST /commerce`) - Approved template with an `ORDER_DETAILS` button  Use this method when you need structured fields (`order`, `referenceId`, `currency`, `paymentSettings`). The API appends a template button `sub_type: order_details` and sends via the same path as `POST /sendTemplate`.  Works **outside the 24-hour session window** (template message).  You can also send the same payload yourself with `POST /sendTemplate` by including a button component in `params`:  ```json {   \"type\": \"button\",   \"sub_type\": \"order_details\",   \"index\": 0,   \"parameters\": [{     \"type\": \"action\",     \"action\": {       \"order_details\": {         \"reference_id\": \"order-123\",         \"currency\": \"INR\",         \"order\": { \"status\": \"pending\", \"items\": [], \"subtotal\": { \"offset\": 100, \"value\": 50000 } }       }     }   }] } ``` 
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendOrderDetailsRequest: (body)  
     - returns: RequestBuilder<MessageSentResponse> 
     */
    open class func sendOrderDetailsWithRequestBuilder(token: String, sendOrderDetailsRequest: SendOrderDetailsRequest) -> RequestBuilder<MessageSentResponse> {
        let localVariablePath = "/sendOrderDetails"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sendOrderDetailsRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageSentResponse>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Send payment request (regional)
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendPaymentRequestRequest: (body)  
     - returns: MessageSentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func sendPaymentRequest(token: String, sendPaymentRequestRequest: SendPaymentRequestRequest) async throws -> MessageSentResponse {
        return try await sendPaymentRequestWithRequestBuilder(token: token, sendPaymentRequestRequest: sendPaymentRequestRequest).execute().body
    }

    /**
     Send payment request (regional)
     - POST /sendPaymentRequest
     - Send a regional payment request interactive message (beta scaffold). `region` must be IN, SG, or BR. Payload shape follows Meta regional payments docs; verify on stage before production use. Full regional builders are not implemented yet. 
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendPaymentRequestRequest: (body)  
     - returns: RequestBuilder<MessageSentResponse> 
     */
    open class func sendPaymentRequestWithRequestBuilder(token: String, sendPaymentRequestRequest: SendPaymentRequestRequest) -> RequestBuilder<MessageSentResponse> {
        let localVariablePath = "/sendPaymentRequest"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sendPaymentRequestRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageSentResponse>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Send a Product
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter requestBody: (body)  (optional)
     - returns: MessageSentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func sendProduct(token: String, requestBody: [String: AnyCodable]? = nil) async throws -> MessageSentResponse {
        return try await sendProductWithRequestBuilder(token: token, requestBody: requestBody).execute().body
    }

    /**
     Send a Product
     - POST /sendProduct
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter requestBody: (body)  (optional)
     - returns: RequestBuilder<MessageSentResponse> 
     */
    open class func sendProductWithRequestBuilder(token: String, requestBody: [String: AnyCodable]? = nil) -> RequestBuilder<MessageSentResponse> {
        let localVariablePath = "/sendProduct"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestBody)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageSentResponse>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Send Reaction
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendReactionRequest: (body)  (optional)
     - returns: MessageSentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func sendReaction(token: String, sendReactionRequest: SendReactionRequest? = nil) async throws -> MessageSentResponse {
        return try await sendReactionWithRequestBuilder(token: token, sendReactionRequest: sendReactionRequest).execute().body
    }

    /**
     Send Reaction
     - POST /sendReaction
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendReactionRequest: (body)  (optional)
     - returns: RequestBuilder<MessageSentResponse> 
     */
    open class func sendReactionWithRequestBuilder(token: String, sendReactionRequest: SendReactionRequest? = nil) -> RequestBuilder<MessageSentResponse> {
        let localVariablePath = "/sendReaction"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sendReactionRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageSentResponse>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Send sticker message
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendStickerRequest: (body)  
     - returns: MessageSentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func sendSticker(token: String, sendStickerRequest: SendStickerRequest) async throws -> MessageSentResponse {
        return try await sendStickerWithRequestBuilder(token: token, sendStickerRequest: sendStickerRequest).execute().body
    }

    /**
     Send sticker message
     - POST /sendSticker
     - Send a WhatsApp sticker by mediaId or link URL.
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendStickerRequest: (body)  
     - returns: RequestBuilder<MessageSentResponse> 
     */
    open class func sendStickerWithRequestBuilder(token: String, sendStickerRequest: SendStickerRequest) -> RequestBuilder<MessageSentResponse> {
        let localVariablePath = "/sendSticker"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sendStickerRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageSentResponse>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
