//
// ProfileAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ProfileAPI {

    /**
     Get Profile Info
     
     - parameter token: (query) JWT token or API key for authorization 
     - returns: ProfileInfo
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getMe(token: String) async throws -> ProfileInfo {
        return try await getMeWithRequestBuilder(token: token).execute().body
    }

    /**
     Get Profile Info
     - GET /me
     - Get WhatsApp Business Account profile information
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - returns: RequestBuilder<ProfileInfo> 
     */
    open class func getMeWithRequestBuilder(token: String) -> RequestBuilder<ProfileInfo> {
        let localVariablePath = "/me"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProfileInfo>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update profile info
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter updateMeRequest: (body)  (optional)
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateMe(token: String, updateMeRequest: UpdateMeRequest? = nil) async throws -> [String: AnyCodable] {
        return try await updateMeWithRequestBuilder(token: token, updateMeRequest: updateMeRequest).execute().body
    }

    /**
     Update profile info
     - POST /me
     - Update WhatsApp Business Account profile fields. At least one of about, description, email, photo, address, vertical, websites is required. Blocked when the channel subscription limit is exceeded. 
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter updateMeRequest: (body)  (optional)
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func updateMeWithRequestBuilder(token: String, updateMeRequest: UpdateMeRequest? = nil) -> RequestBuilder<[String: AnyCodable]> {
        let localVariablePath = "/me"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateMeRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
