//
// WebhooksAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class WebhooksAPI {

    /**
     Get webhook URL
     
     - parameter token: (query) JWT token or API key for authorization 
     - returns: GetWebhook200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getWebhook(token: String) async throws -> GetWebhook200Response {
        return try await getWebhookWithRequestBuilder(token: token).execute().body
    }

    /**
     Get webhook URL
     - GET /webhook
     - Returns the configured client webhook URL for this channel.
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - returns: RequestBuilder<GetWebhook200Response> 
     */
    open class func getWebhookWithRequestBuilder(token: String) -> RequestBuilder<GetWebhook200Response> {
        let localVariablePath = "/webhook"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetWebhook200Response>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Set webhook URL
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter getWebhook200Response: (body)  (optional)
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func setWebhook(token: String, getWebhook200Response: GetWebhook200Response? = nil) async throws -> [String: AnyCodable] {
        return try await setWebhookWithRequestBuilder(token: token, getWebhook200Response: getWebhook200Response).execute().body
    }

    /**
     Set webhook URL
     - POST /webhook
     - Configure the client webhook URL for inbound events.  WhatsApp **Calling** events (`field=calls`) are forwarded as passthrough payloads with `type: \"calls\"` and `instanceId` (connect / status / terminate). Call permission replies arrive on the normal messages path (`call_permission_reply`). Details: **Calling** tag. 
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter getWebhook200Response: (body)  (optional)
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func setWebhookWithRequestBuilder(token: String, getWebhook200Response: GetWebhook200Response? = nil) -> RequestBuilder<[String: AnyCodable]> {
        let localVariablePath = "/webhook"
        let localVariableURLString = OneMsgSdkAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: getWebhook200Response)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = OneMsgSdkAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
