//
// ChannelAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ChannelAPI {

    /**
     Get conversational automation settings
     
     - parameter token: (query) JWT token or API key for authorization 
     - returns: ConversationalAutomation
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getConversationalAutomation(token: String) async throws -> ConversationalAutomation {
        return try await getConversationalAutomationWithRequestBuilder(token: token).execute().body
    }

    /**
     Get conversational automation settings
     - GET /conversationalAutomation
     - Get WhatsApp conversational components for the channel (welcome message, ice-breaker prompts, and slash commands).  Proxies Meta/360dialog `GET /conversational_automation`.  When `enable_welcome_message` is true and a user opens chat for the first time, Meta delivers a webhook message with `type: request_welcome`. The inbound formatter exposes that as `type: \"request_welcome\"` and `meta.request_welcome: true` so your webhook can send a custom welcome reply. 
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - returns: RequestBuilder<ConversationalAutomation> 
     */
    open class func getConversationalAutomationWithRequestBuilder(token: String) -> RequestBuilder<ConversationalAutomation> {
        let localVariablePath = "/conversationalAutomation"
        let localVariableURLString = OneMsgChatApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ConversationalAutomation>.Type = OneMsgChatApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get channel status
     
     - parameter token: (query) JWT token or API key for authorization 
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getStatus(token: String) async throws -> [String: AnyCodable] {
        return try await getStatusWithRequestBuilder(token: token).execute().body
    }

    /**
     Get channel status
     - GET /status
     - Returns WhatsApp Business API client connection status.
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func getStatusWithRequestBuilder(token: String) -> RequestBuilder<[String: AnyCodable]> {
        let localVariablePath = "/status"
        let localVariableURLString = OneMsgChatApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = OneMsgChatApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Set conversational automation settings
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter conversationalAutomation: (body)  
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func setConversationalAutomation(token: String, conversationalAutomation: ConversationalAutomation) async throws -> [String: AnyCodable] {
        return try await setConversationalAutomationWithRequestBuilder(token: token, conversationalAutomation: conversationalAutomation).execute().body
    }

    /**
     Set conversational automation settings
     - POST /conversationalAutomation
     - Update WhatsApp conversational components.  Allowed body fields (others are ignored): - `enable_welcome_message` (boolean) - `prompts` (string[], max 4, each ≤ 80 chars) - `commands` (`{ command_name, command_description }[]`)  Proxies Meta/360dialog `POST /conversational_automation`. 
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter conversationalAutomation: (body)  
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func setConversationalAutomationWithRequestBuilder(token: String, conversationalAutomation: ConversationalAutomation) -> RequestBuilder<[String: AnyCodable]> {
        let localVariablePath = "/conversationalAutomation"
        let localVariableURLString = OneMsgChatApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: conversationalAutomation)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = OneMsgChatApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
