//
// GroupsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class GroupsAPI {

    /**
     Create Group
     
     - parameter token: (query) JWT token or API key for authorization 
     - returns: CreateGroups200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createGroups(token: String) async throws -> CreateGroups200Response {
        return try await createGroupsWithRequestBuilder(token: token).execute().body
    }

    /**
     Create Group
     - POST /groups
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - returns: RequestBuilder<CreateGroups200Response> 
     */
    open class func createGroupsWithRequestBuilder(token: String) -> RequestBuilder<CreateGroups200Response> {
        let localVariablePath = "/groups"
        let localVariableURLString = OneMsgChatApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateGroups200Response>.Type = OneMsgChatApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update Group Info
     
     - parameter groupId: (path)  
     - parameter token: (query) JWT token or API key for authorization 
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createGroupsGroupId(groupId: String, token: String) async throws -> [String: AnyCodable] {
        return try await createGroupsGroupIdWithRequestBuilder(groupId: groupId, token: token).execute().body
    }

    /**
     Update Group Info
     - POST /groups/{groupId}
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter groupId: (path)  
     - parameter token: (query) JWT token or API key for authorization 
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func createGroupsGroupIdWithRequestBuilder(groupId: String, token: String) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/groups/{groupId}"
        let groupIdPreEscape = "\(APIHelper.mapValueToPathItem(groupId))"
        let groupIdPostEscape = groupIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{groupId}", with: groupIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OneMsgChatApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = OneMsgChatApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Reset Invite Link
     
     - parameter groupId: (path)  
     - parameter token: (query) JWT token or API key for authorization 
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createGroupsGroupIdInvitelink(groupId: String, token: String) async throws -> [String: AnyCodable] {
        return try await createGroupsGroupIdInvitelinkWithRequestBuilder(groupId: groupId, token: token).execute().body
    }

    /**
     Reset Invite Link
     - POST /groups/{groupId}/inviteLink
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter groupId: (path)  
     - parameter token: (query) JWT token or API key for authorization 
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func createGroupsGroupIdInvitelinkWithRequestBuilder(groupId: String, token: String) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/groups/{groupId}/inviteLink"
        let groupIdPreEscape = "\(APIHelper.mapValueToPathItem(groupId))"
        let groupIdPostEscape = groupIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{groupId}", with: groupIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OneMsgChatApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = OneMsgChatApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete Group
     
     - parameter groupId: (path)  
     - parameter token: (query) JWT token or API key for authorization 
     - returns: DeleteGroupsGroupId200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteGroupsGroupId(groupId: String, token: String) async throws -> DeleteGroupsGroupId200Response {
        return try await deleteGroupsGroupIdWithRequestBuilder(groupId: groupId, token: token).execute().body
    }

    /**
     Delete Group
     - DELETE /groups/{groupId}
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter groupId: (path)  
     - parameter token: (query) JWT token or API key for authorization 
     - returns: RequestBuilder<DeleteGroupsGroupId200Response> 
     */
    open class func deleteGroupsGroupIdWithRequestBuilder(groupId: String, token: String) -> RequestBuilder<DeleteGroupsGroupId200Response> {
        var localVariablePath = "/groups/{groupId}"
        let groupIdPreEscape = "\(APIHelper.mapValueToPathItem(groupId))"
        let groupIdPostEscape = groupIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{groupId}", with: groupIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OneMsgChatApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeleteGroupsGroupId200Response>.Type = OneMsgChatApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Group Info
     
     - parameter groupId: (path)  
     - parameter token: (query) JWT token or API key for authorization 
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getGroupsGroupId(groupId: String, token: String) async throws -> [String: AnyCodable] {
        return try await getGroupsGroupIdWithRequestBuilder(groupId: groupId, token: token).execute().body
    }

    /**
     Get Group Info
     - GET /groups/{groupId}
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter groupId: (path)  
     - parameter token: (query) JWT token or API key for authorization 
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func getGroupsGroupIdWithRequestBuilder(groupId: String, token: String) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/groups/{groupId}"
        let groupIdPreEscape = "\(APIHelper.mapValueToPathItem(groupId))"
        let groupIdPostEscape = groupIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{groupId}", with: groupIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OneMsgChatApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = OneMsgChatApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Invite Link
     
     - parameter groupId: (path)  
     - parameter token: (query) JWT token or API key for authorization 
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getGroupsGroupIdInvitelink(groupId: String, token: String) async throws -> [String: AnyCodable] {
        return try await getGroupsGroupIdInvitelinkWithRequestBuilder(groupId: groupId, token: token).execute().body
    }

    /**
     Get Invite Link
     - GET /groups/{groupId}/inviteLink
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter groupId: (path)  
     - parameter token: (query) JWT token or API key for authorization 
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func getGroupsGroupIdInvitelinkWithRequestBuilder(groupId: String, token: String) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/groups/{groupId}/inviteLink"
        let groupIdPreEscape = "\(APIHelper.mapValueToPathItem(groupId))"
        let groupIdPostEscape = groupIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{groupId}", with: groupIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OneMsgChatApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = OneMsgChatApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Groups List
     
     - parameter token: (query) JWT token or API key for authorization 
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listGroups(token: String) async throws -> [String: AnyCodable] {
        return try await listGroupsWithRequestBuilder(token: token).execute().body
    }

    /**
     Get Groups List
     - GET /groups
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func listGroupsWithRequestBuilder(token: String) -> RequestBuilder<[String: AnyCodable]> {
        let localVariablePath = "/groups"
        let localVariableURLString = OneMsgChatApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = OneMsgChatApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
