//
// TemplatesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class TemplatesAPI {

    /**
     Create message template
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter addTemplateRequest: (body)  (optional)
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func addTemplate(token: String, addTemplateRequest: AddTemplateRequest? = nil) async throws -> [String: AnyCodable] {
        return try await addTemplateWithRequestBuilder(token: token, addTemplateRequest: addTemplateRequest).execute().body
    }

    /**
     Create message template
     - POST /addTemplate
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter addTemplateRequest: (body)  (optional)
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func addTemplateWithRequestBuilder(token: String, addTemplateRequest: AddTemplateRequest? = nil) -> RequestBuilder<[String: AnyCodable]> {
        let localVariablePath = "/addTemplate"
        let localVariableURLString = OneMsgChatApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: addTemplateRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = OneMsgChatApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get templates list
     
     - parameter token: (query) JWT token or API key for authorization 
     - returns: ListTemplates200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listTemplates(token: String) async throws -> ListTemplates200Response {
        return try await listTemplatesWithRequestBuilder(token: token).execute().body
    }

    /**
     Get templates list
     - GET /templates
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - returns: RequestBuilder<ListTemplates200Response> 
     */
    open class func listTemplatesWithRequestBuilder(token: String) -> RequestBuilder<ListTemplates200Response> {
        let localVariablePath = "/templates"
        let localVariableURLString = OneMsgChatApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListTemplates200Response>.Type = OneMsgChatApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Remove message template
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter requestBody: (body)  (optional)
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func removeTemplate(token: String, requestBody: [String: AnyCodable]? = nil) async throws -> [String: AnyCodable] {
        return try await removeTemplateWithRequestBuilder(token: token, requestBody: requestBody).execute().body
    }

    /**
     Remove message template
     - POST /removeTemplate
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter requestBody: (body)  (optional)
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func removeTemplateWithRequestBuilder(token: String, requestBody: [String: AnyCodable]? = nil) -> RequestBuilder<[String: AnyCodable]> {
        let localVariablePath = "/removeTemplate"
        let localVariableURLString = OneMsgChatApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestBody)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = OneMsgChatApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Send Template Message
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendTemplateRequest: (body)  (optional)
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func sendTemplate(token: String, sendTemplateRequest: SendTemplateRequest? = nil) async throws -> [String: AnyCodable] {
        return try await sendTemplateWithRequestBuilder(token: token, sendTemplateRequest: sendTemplateRequest).execute().body
    }

    /**
     Send Template Message
     - POST /sendTemplate
     - Send a WhatsApp template message (works outside the 24-hour session window).  Supported `params` button `sub_type` values include: `url`, `quick_reply`, `copy_code` / `coupon_code`, `catalog`, `flow`, `limited_time_offer`, and **`order_details`** (WhatsApp Payments **India only** — requires an approved Utility template with an ORDER_DETAILS button).  For India order/invoice payments outside 24h, include a button component:  ```json {   \"type\": \"button\",   \"sub_type\": \"order_details\",   \"index\": 0,   \"parameters\": [{     \"type\": \"action\",     \"action\": { \"order_details\": { \"reference_id\": \"...\", \"currency\": \"INR\", \"order\": {} } }   }] } ```  Convenience wrapper with structured fields: `POST /sendOrderDetails`. 
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter sendTemplateRequest: (body)  (optional)
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func sendTemplateWithRequestBuilder(token: String, sendTemplateRequest: SendTemplateRequest? = nil) -> RequestBuilder<[String: AnyCodable]> {
        let localVariablePath = "/sendTemplate"
        let localVariableURLString = OneMsgChatApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sendTemplateRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = OneMsgChatApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
