//
// UsersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class UsersAPI {

    /**
     Block WhatsApp user
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter blockUserRequest: (body)  
     - returns: SuccessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func blockUser(token: String, blockUserRequest: BlockUserRequest) async throws -> SuccessResponse {
        return try await blockUserWithRequestBuilder(token: token, blockUserRequest: blockUserRequest).execute().body
    }

    /**
     Block WhatsApp user
     - POST /blockUser
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter blockUserRequest: (body)  
     - returns: RequestBuilder<SuccessResponse> 
     */
    open class func blockUserWithRequestBuilder(token: String, blockUserRequest: BlockUserRequest) -> RequestBuilder<SuccessResponse> {
        let localVariablePath = "/blockUser"
        let localVariableURLString = OneMsgChatApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: blockUserRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponse>.Type = OneMsgChatApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List blocked WhatsApp users
     
     - parameter token: (query) JWT token or API key for authorization 
     - returns: ListBlockedUsers200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listBlockedUsers(token: String) async throws -> ListBlockedUsers200Response {
        return try await listBlockedUsersWithRequestBuilder(token: token).execute().body
    }

    /**
     List blocked WhatsApp users
     - GET /blockedUsers
     - Returns users currently blocked on this WhatsApp channel (WABA `GET /block_users`). Same channel token auth as `blockUser` / `unblockUser`. 
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - returns: RequestBuilder<ListBlockedUsers200Response> 
     */
    open class func listBlockedUsersWithRequestBuilder(token: String) -> RequestBuilder<ListBlockedUsers200Response> {
        let localVariablePath = "/blockedUsers"
        let localVariableURLString = OneMsgChatApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListBlockedUsers200Response>.Type = OneMsgChatApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Unblock WhatsApp user
     
     - parameter token: (query) JWT token or API key for authorization 
     - parameter blockUserRequest: (body)  
     - returns: SuccessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func unblockUser(token: String, blockUserRequest: BlockUserRequest) async throws -> SuccessResponse {
        return try await unblockUserWithRequestBuilder(token: token, blockUserRequest: blockUserRequest).execute().body
    }

    /**
     Unblock WhatsApp user
     - POST /unblockUser
     - API Key:
       - type: apiKey token (QUERY)
       - name: tokenAuth
     - parameter token: (query) JWT token or API key for authorization 
     - parameter blockUserRequest: (body)  
     - returns: RequestBuilder<SuccessResponse> 
     */
    open class func unblockUserWithRequestBuilder(token: String, blockUserRequest: BlockUserRequest) -> RequestBuilder<SuccessResponse> {
        let localVariablePath = "/unblockUser"
        let localVariableURLString = OneMsgChatApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: blockUserRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponse>.Type = OneMsgChatApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
