//
// AddTemplateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AddTemplateRequest: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var category: String?
    public var language: String?
    public var components: [[String: AnyCodable]]?

    public init(name: String? = nil, category: String? = nil, language: String? = nil, components: [[String: AnyCodable]]? = nil) {
        self.name = name
        self.category = category
        self.language = language
        self.components = components
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case category
        case language
        case components
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(components, forKey: .components)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        name = try container.decodeIfPresent(String.self, forKey: .name)
        category = try container.decodeIfPresent(String.self, forKey: .category)
        language = try container.decodeIfPresent(String.self, forKey: .language)
        components = try container.decodeIfPresent([[String: AnyCodable]].self, forKey: .components)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("name")
        nonAdditionalPropertyKeys.insert("category")
        nonAdditionalPropertyKeys.insert("language")
        nonAdditionalPropertyKeys.insert("components")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

