//
// CreateReadMessageRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateReadMessageRequest: Codable, JSONEncodable, Hashable {

    public var messageId: String?
    public var msgId: String?
    /** Show WhatsApp typing indicator (max 25s or until reply) */
    public var typingIndicator: Bool? = false

    public init(messageId: String? = nil, msgId: String? = nil, typingIndicator: Bool? = false) {
        self.messageId = messageId
        self.msgId = msgId
        self.typingIndicator = typingIndicator
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case messageId
        case msgId
        case typingIndicator
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(messageId, forKey: .messageId)
        try container.encodeIfPresent(msgId, forKey: .msgId)
        try container.encodeIfPresent(typingIndicator, forKey: .typingIndicator)
    }
}

