//
// GetWhatsappBusinessEncryption200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetWhatsappBusinessEncryption200Response: Codable, JSONEncodable, Hashable {

    public enum BusinessPublicKeySignatureStatus: String, Codable, CaseIterable {
        case valid = "VALID"
        case mismatch = "MISMATCH"
    }
    /** Stored 2048-bit RSA public key (PEM) */
    public var businessPublicKey: String?
    public var businessPublicKeySignatureStatus: BusinessPublicKeySignatureStatus?
    public var data: [[String: AnyCodable]]?

    public init(businessPublicKey: String? = nil, businessPublicKeySignatureStatus: BusinessPublicKeySignatureStatus? = nil, data: [[String: AnyCodable]]? = nil) {
        self.businessPublicKey = businessPublicKey
        self.businessPublicKeySignatureStatus = businessPublicKeySignatureStatus
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case businessPublicKey = "business_public_key"
        case businessPublicKeySignatureStatus = "business_public_key_signature_status"
        case data
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(businessPublicKey, forKey: .businessPublicKey)
        try container.encodeIfPresent(businessPublicKeySignatureStatus, forKey: .businessPublicKeySignatureStatus)
        try container.encodeIfPresent(data, forKey: .data)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        businessPublicKey = try container.decodeIfPresent(String.self, forKey: .businessPublicKey)
        businessPublicKeySignatureStatus = try container.decodeIfPresent(BusinessPublicKeySignatureStatus.self, forKey: .businessPublicKeySignatureStatus)
        data = try container.decodeIfPresent([[String: AnyCodable]].self, forKey: .data)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("business_public_key")
        nonAdditionalPropertyKeys.insert("business_public_key_signature_status")
        nonAdditionalPropertyKeys.insert("data")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

