//
// ListMessages200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListMessages200Response: Codable, JSONEncodable, Hashable {

    public var notice: String?
    public var messages: [[String: AnyCodable]]?

    public init(notice: String? = nil, messages: [[String: AnyCodable]]? = nil) {
        self.notice = notice
        self.messages = messages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case notice
        case messages
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(notice, forKey: .notice)
        try container.encodeIfPresent(messages, forKey: .messages)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        notice = try container.decodeIfPresent(String.self, forKey: .notice)
        messages = try container.decodeIfPresent([[String: AnyCodable]].self, forKey: .messages)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("notice")
        nonAdditionalPropertyKeys.insert("messages")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

