//
// MessageSentResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response for successfully sent message */
public struct MessageSentResponse: Codable, JSONEncodable, Hashable {

    /** Whether the message was successfully queued for sending */
    public var sent: Bool?
    /** Message ID */
    public var id: String?
    /** Status message */
    public var message: String?
    /** Detailed description */
    public var description: String?

    public init(sent: Bool? = nil, id: String? = nil, message: String? = nil, description: String? = nil) {
        self.sent = sent
        self.id = id
        self.message = message
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sent
        case id
        case message
        case description
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(sent, forKey: .sent)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(description, forKey: .description)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        sent = try container.decodeIfPresent(Bool.self, forKey: .sent)
        id = try container.decodeIfPresent(String.self, forKey: .id)
        message = try container.decodeIfPresent(String.self, forKey: .message)
        description = try container.decodeIfPresent(String.self, forKey: .description)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("sent")
        nonAdditionalPropertyKeys.insert("id")
        nonAdditionalPropertyKeys.insert("message")
        nonAdditionalPropertyKeys.insert("description")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension MessageSentResponse: Identifiable {}
