//
// RetrieveMedia200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RetrieveMedia200Response: Codable, JSONEncodable, Hashable {

    public var url: String?
    public var mimeType: String?
    public var sha256: String?
    public var fileSize: Int?
    public var id: String?

    public init(url: String? = nil, mimeType: String? = nil, sha256: String? = nil, fileSize: Int? = nil, id: String? = nil) {
        self.url = url
        self.mimeType = mimeType
        self.sha256 = sha256
        self.fileSize = fileSize
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case mimeType
        case sha256
        case fileSize
        case id
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(mimeType, forKey: .mimeType)
        try container.encodeIfPresent(sha256, forKey: .sha256)
        try container.encodeIfPresent(fileSize, forKey: .fileSize)
        try container.encodeIfPresent(id, forKey: .id)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        url = try container.decodeIfPresent(String.self, forKey: .url)
        mimeType = try container.decodeIfPresent(String.self, forKey: .mimeType)
        sha256 = try container.decodeIfPresent(String.self, forKey: .sha256)
        fileSize = try container.decodeIfPresent(Int.self, forKey: .fileSize)
        id = try container.decodeIfPresent(String.self, forKey: .id)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("url")
        nonAdditionalPropertyKeys.insert("mimeType")
        nonAdditionalPropertyKeys.insert("sha256")
        nonAdditionalPropertyKeys.insert("fileSize")
        nonAdditionalPropertyKeys.insert("id")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension RetrieveMedia200Response: Identifiable {}
