//
// SendListRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendListRequest: Codable, JSONEncodable, Hashable {

    public var phone: String?
    public var body: String?
    public var buttonText: String?
    public var action: String?
    public var sections: [SendListRequestSectionsInner]?

    public init(phone: String? = nil, body: String? = nil, buttonText: String? = nil, action: String? = nil, sections: [SendListRequestSectionsInner]? = nil) {
        self.phone = phone
        self.body = body
        self.buttonText = buttonText
        self.action = action
        self.sections = sections
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case phone
        case body
        case buttonText
        case action
        case sections
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(body, forKey: .body)
        try container.encodeIfPresent(buttonText, forKey: .buttonText)
        try container.encodeIfPresent(action, forKey: .action)
        try container.encodeIfPresent(sections, forKey: .sections)
    }
}

