//
// SendContactRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendContactRequest: Codable, JSONEncodable, Hashable {

    public var phone: String?
    public var contacts: [SendContactRequestContactsInner]?

    public init(phone: String? = nil, contacts: [SendContactRequestContactsInner]? = nil) {
        self.phone = phone
        self.contacts = contacts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case phone
        case contacts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(contacts, forKey: .contacts)
    }
}

