//
// SendLocationRequest1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendLocationRequest1: Codable, JSONEncodable, Hashable {

    public var lat: String
    public var lng: String
    public var address: String?
    public var name: String?
    public var quotedMsgId: String?
    public var chatId: String?
    public var phone: Int?

    public init(lat: String, lng: String, address: String? = nil, name: String? = nil, quotedMsgId: String? = nil, chatId: String? = nil, phone: Int? = nil) {
        self.lat = lat
        self.lng = lng
        self.address = address
        self.name = name
        self.quotedMsgId = quotedMsgId
        self.chatId = chatId
        self.phone = phone
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lat
        case lng
        case address
        case name
        case quotedMsgId
        case chatId
        case phone
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(lat, forKey: .lat)
        try container.encode(lng, forKey: .lng)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(quotedMsgId, forKey: .quotedMsgId)
        try container.encodeIfPresent(chatId, forKey: .chatId)
        try container.encodeIfPresent(phone, forKey: .phone)
    }
}

