//
// SendPaymentRequestRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendPaymentRequestRequest: Codable, JSONEncodable, Hashable {

    public enum Region: String, Codable, CaseIterable {
        case _in = "IN"
        case sg = "SG"
        case br = "BR"
    }
    public var phone: Int
    public var region: Region
    public var body: String?
    public var interactive: [String: AnyCodable]?
    public var action: [String: AnyCodable]?

    public init(phone: Int, region: Region, body: String? = nil, interactive: [String: AnyCodable]? = nil, action: [String: AnyCodable]? = nil) {
        self.phone = phone
        self.region = region
        self.body = body
        self.interactive = interactive
        self.action = action
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case phone
        case region
        case body
        case interactive
        case action
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(phone, forKey: .phone)
        try container.encode(region, forKey: .region)
        try container.encodeIfPresent(body, forKey: .body)
        try container.encodeIfPresent(interactive, forKey: .interactive)
        try container.encodeIfPresent(action, forKey: .action)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        phone = try container.decode(Int.self, forKey: .phone)
        region = try container.decode(Region.self, forKey: .region)
        body = try container.decodeIfPresent(String.self, forKey: .body)
        interactive = try container.decodeIfPresent([String: AnyCodable].self, forKey: .interactive)
        action = try container.decodeIfPresent([String: AnyCodable].self, forKey: .action)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("phone")
        nonAdditionalPropertyKeys.insert("region")
        nonAdditionalPropertyKeys.insert("body")
        nonAdditionalPropertyKeys.insert("interactive")
        nonAdditionalPropertyKeys.insert("action")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

