//
// SendOrderDetailsRequestOrder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Order payload for the ORDER_DETAILS button. Typical fields: status, items[], subtotal, tax, shipping, discount. Amount objects use &#x60;{ \&quot;offset\&quot;: 100, \&quot;value\&quot;: &lt;minor_units&gt; }&#x60; (e.g. value 50000 with offset 100 &#x3D; ₹500.00).  */
public struct SendOrderDetailsRequestOrder: Codable, JSONEncodable, Hashable {

    /** Order status */
    public var status: String?
    /** Line items */
    public var items: [SendOrderDetailsRequestOrderItemsInner]
    public var subtotal: SendOrderDetailsRequestOrderItemsInnerAmount?
    public var tax: [String: AnyCodable]?
    public var shipping: [String: AnyCodable]?
    public var discount: [String: AnyCodable]?

    public init(status: String? = nil, items: [SendOrderDetailsRequestOrderItemsInner], subtotal: SendOrderDetailsRequestOrderItemsInnerAmount? = nil, tax: [String: AnyCodable]? = nil, shipping: [String: AnyCodable]? = nil, discount: [String: AnyCodable]? = nil) {
        self.status = status
        self.items = items
        self.subtotal = subtotal
        self.tax = tax
        self.shipping = shipping
        self.discount = discount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case items
        case subtotal
        case tax
        case shipping
        case discount
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encode(items, forKey: .items)
        try container.encodeIfPresent(subtotal, forKey: .subtotal)
        try container.encodeIfPresent(tax, forKey: .tax)
        try container.encodeIfPresent(shipping, forKey: .shipping)
        try container.encodeIfPresent(discount, forKey: .discount)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        status = try container.decodeIfPresent(String.self, forKey: .status)
        items = try container.decode([SendOrderDetailsRequestOrderItemsInner].self, forKey: .items)
        subtotal = try container.decodeIfPresent(SendOrderDetailsRequestOrderItemsInnerAmount.self, forKey: .subtotal)
        tax = try container.decodeIfPresent([String: AnyCodable].self, forKey: .tax)
        shipping = try container.decodeIfPresent([String: AnyCodable].self, forKey: .shipping)
        discount = try container.decodeIfPresent([String: AnyCodable].self, forKey: .discount)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("status")
        nonAdditionalPropertyKeys.insert("items")
        nonAdditionalPropertyKeys.insert("subtotal")
        nonAdditionalPropertyKeys.insert("tax")
        nonAdditionalPropertyKeys.insert("shipping")
        nonAdditionalPropertyKeys.insert("discount")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

