//
// SendButtonRequestSectionsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendButtonRequestSectionsInner: Codable, JSONEncodable, Hashable {

    public var type: String?
    public var reply: SendButtonRequestSectionsInnerReply?

    public init(type: String? = nil, reply: SendButtonRequestSectionsInnerReply? = nil) {
        self.type = type
        self.reply = reply
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case reply
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(reply, forKey: .reply)
    }
}

