//
// SendOrderDetailsRequestOrderItemsInnerAmount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendOrderDetailsRequestOrderItemsInnerAmount: Codable, JSONEncodable, Hashable {

    public var offset: Int?
    public var value: Int?

    public init(offset: Int? = nil, value: Int? = nil) {
        self.offset = offset
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case offset
        case value
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(offset, forKey: .offset)
        try container.encodeIfPresent(value, forKey: .value)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        offset = try container.decodeIfPresent(Int.self, forKey: .offset)
        value = try container.decodeIfPresent(Int.self, forKey: .value)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("offset")
        nonAdditionalPropertyKeys.insert("value")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

