//
// SendTemplateRequestLanguage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendTemplateRequestLanguage: Codable, JSONEncodable, Hashable {

    public var policy: String?
    public var code: String?

    public init(policy: String? = nil, code: String? = nil) {
        self.policy = policy
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case policy
        case code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(policy, forKey: .policy)
        try container.encodeIfPresent(code, forKey: .code)
    }
}

