//
// SendStickerRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendStickerRequest: Codable, JSONEncodable, Hashable {

    public var phone: Int?
    public var chatId: String?
    /** WABA media id from uploadMedia */
    public var mediaId: String?
    /** Public URL to webp sticker */
    public var link: String?
    public var quotedMsgId: String?

    public init(phone: Int? = nil, chatId: String? = nil, mediaId: String? = nil, link: String? = nil, quotedMsgId: String? = nil) {
        self.phone = phone
        self.chatId = chatId
        self.mediaId = mediaId
        self.link = link
        self.quotedMsgId = quotedMsgId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case phone
        case chatId
        case mediaId
        case link
        case quotedMsgId
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(chatId, forKey: .chatId)
        try container.encodeIfPresent(mediaId, forKey: .mediaId)
        try container.encodeIfPresent(link, forKey: .link)
        try container.encodeIfPresent(quotedMsgId, forKey: .quotedMsgId)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        phone = try container.decodeIfPresent(Int.self, forKey: .phone)
        chatId = try container.decodeIfPresent(String.self, forKey: .chatId)
        mediaId = try container.decodeIfPresent(String.self, forKey: .mediaId)
        link = try container.decodeIfPresent(String.self, forKey: .link)
        quotedMsgId = try container.decodeIfPresent(String.self, forKey: .quotedMsgId)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("phone")
        nonAdditionalPropertyKeys.insert("chatId")
        nonAdditionalPropertyKeys.insert("mediaId")
        nonAdditionalPropertyKeys.insert("link")
        nonAdditionalPropertyKeys.insert("quotedMsgId")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

