//
// SendCarouselRequest1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendCarouselRequest1: Codable, JSONEncodable, Hashable {

    public var body: String?
    public var params: [AnyCodable]
    public var quotedMsgId: String?
    public var chatId: String?
    public var phone: Int?

    public init(body: String? = nil, params: [AnyCodable], quotedMsgId: String? = nil, chatId: String? = nil, phone: Int? = nil) {
        self.body = body
        self.params = params
        self.quotedMsgId = quotedMsgId
        self.chatId = chatId
        self.phone = phone
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case body
        case params
        case quotedMsgId
        case chatId
        case phone
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(body, forKey: .body)
        try container.encode(params, forKey: .params)
        try container.encodeIfPresent(quotedMsgId, forKey: .quotedMsgId)
        try container.encodeIfPresent(chatId, forKey: .chatId)
        try container.encodeIfPresent(phone, forKey: .phone)
    }
}

