//
// SendListRequestSectionsInnerRowsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendListRequestSectionsInnerRowsInner: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var title: String?
    public var description: String?

    public init(id: String? = nil, title: String? = nil, description: String? = nil) {
        self.id = id
        self.title = title
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SendListRequestSectionsInnerRowsInner: Identifiable {}
