//
// SendOrderDetailsRequestOrderItemsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendOrderDetailsRequestOrderItemsInner: Codable, JSONEncodable, Hashable {

    public var retailerId: String?
    public var name: String?
    public var quantity: Int?
    public var amount: SendOrderDetailsRequestOrderItemsInnerAmount?

    public init(retailerId: String? = nil, name: String? = nil, quantity: Int? = nil, amount: SendOrderDetailsRequestOrderItemsInnerAmount? = nil) {
        self.retailerId = retailerId
        self.name = name
        self.quantity = quantity
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case retailerId = "retailer_id"
        case name
        case quantity
        case amount
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(retailerId, forKey: .retailerId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(quantity, forKey: .quantity)
        try container.encodeIfPresent(amount, forKey: .amount)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        retailerId = try container.decodeIfPresent(String.self, forKey: .retailerId)
        name = try container.decodeIfPresent(String.self, forKey: .name)
        quantity = try container.decodeIfPresent(Int.self, forKey: .quantity)
        amount = try container.decodeIfPresent(SendOrderDetailsRequestOrderItemsInnerAmount.self, forKey: .amount)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("retailer_id")
        nonAdditionalPropertyKeys.insert("name")
        nonAdditionalPropertyKeys.insert("quantity")
        nonAdditionalPropertyKeys.insert("amount")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

