//
// SendTemplateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendTemplateRequest: Codable, JSONEncodable, Hashable {

    public var template: String?
    public var language: SendTemplateRequestLanguage?
    public var namespace: String?
    public var params: [AnyCodable]?
    public var phone: String?
    /** Force Marketing Messages API (POST marketing_messages). If omitted: auto for MARKETING category when channel has mm_lite_enabled and mm_lite_available service settings.  */
    public var useMMlite: Bool?
    /** Sets message_activity_sharing on WABA payload. Enables click tracking webhooks. Requires MM Lite path. Ignored on Cloud API fallback.  */
    public var messageActivitySharing: Bool?
    /** Template message TTL in seconds (message_send_ttl_seconds). MARKETING via MM Lite: 43200–2592000. AUTHENTICATION: 30–900. UTILITY: 30–43200. AUTH/UTILITY also accept -1 (30-day custom TTL).  */
    public var messageSendTtlSeconds: Int?

    public init(template: String? = nil, language: SendTemplateRequestLanguage? = nil, namespace: String? = nil, params: [AnyCodable]? = nil, phone: String? = nil, useMMlite: Bool? = nil, messageActivitySharing: Bool? = nil, messageSendTtlSeconds: Int? = nil) {
        self.template = template
        self.language = language
        self.namespace = namespace
        self.params = params
        self.phone = phone
        self.useMMlite = useMMlite
        self.messageActivitySharing = messageActivitySharing
        self.messageSendTtlSeconds = messageSendTtlSeconds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case template
        case language
        case namespace
        case params
        case phone
        case useMMlite
        case messageActivitySharing
        case messageSendTtlSeconds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(template, forKey: .template)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(namespace, forKey: .namespace)
        try container.encodeIfPresent(params, forKey: .params)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(useMMlite, forKey: .useMMlite)
        try container.encodeIfPresent(messageActivitySharing, forKey: .messageActivitySharing)
        try container.encodeIfPresent(messageSendTtlSeconds, forKey: .messageSendTtlSeconds)
    }
}

