//
// SendOrderDetailsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendOrderDetailsRequest: Codable, JSONEncodable, Hashable {

    /** Recipient phone (India E.164 digits, no +). Use phone or chatId. */
    public var phone: Int?
    /** Recipient chatId (e.g. phone@c.us). Use phone or chatId. */
    public var chatId: String?
    /** Approved Utility template name that includes an ORDER_DETAILS button */
    public var template: String
    /** Template namespace from the channel / template list */
    public var namespace: String
    public var language: SendOrderDetailsRequestLanguage
    /** Extra template components (HEADER / BODY / etc.). If an order_details button is missing, the API appends one from order / referenceId / currency / paymentSettings.  */
    public var params: [[String: AnyCodable]]?
    /** Unique order / payment reference id (maps to reference_id) */
    public var referenceId: String?
    /** Currency code for India payments */
    public var currency: String?
    /** Optional payment settings (UPI / payment gateway / payment link). Forwarded as payment_settings on the order_details action.  */
    public var paymentSettings: [String: AnyCodable]?
    public var order: SendOrderDetailsRequestOrder

    public init(phone: Int? = nil, chatId: String? = nil, template: String, namespace: String, language: SendOrderDetailsRequestLanguage, params: [[String: AnyCodable]]? = nil, referenceId: String? = nil, currency: String? = nil, paymentSettings: [String: AnyCodable]? = nil, order: SendOrderDetailsRequestOrder) {
        self.phone = phone
        self.chatId = chatId
        self.template = template
        self.namespace = namespace
        self.language = language
        self.params = params
        self.referenceId = referenceId
        self.currency = currency
        self.paymentSettings = paymentSettings
        self.order = order
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case phone
        case chatId
        case template
        case namespace
        case language
        case params
        case referenceId
        case currency
        case paymentSettings
        case order
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(chatId, forKey: .chatId)
        try container.encode(template, forKey: .template)
        try container.encode(namespace, forKey: .namespace)
        try container.encode(language, forKey: .language)
        try container.encodeIfPresent(params, forKey: .params)
        try container.encodeIfPresent(referenceId, forKey: .referenceId)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(paymentSettings, forKey: .paymentSettings)
        try container.encode(order, forKey: .order)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        phone = try container.decodeIfPresent(Int.self, forKey: .phone)
        chatId = try container.decodeIfPresent(String.self, forKey: .chatId)
        template = try container.decode(String.self, forKey: .template)
        namespace = try container.decode(String.self, forKey: .namespace)
        language = try container.decode(SendOrderDetailsRequestLanguage.self, forKey: .language)
        params = try container.decodeIfPresent([[String: AnyCodable]].self, forKey: .params)
        referenceId = try container.decodeIfPresent(String.self, forKey: .referenceId)
        currency = try container.decodeIfPresent(String.self, forKey: .currency)
        paymentSettings = try container.decodeIfPresent([String: AnyCodable].self, forKey: .paymentSettings)
        order = try container.decode(SendOrderDetailsRequestOrder.self, forKey: .order)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("phone")
        nonAdditionalPropertyKeys.insert("chatId")
        nonAdditionalPropertyKeys.insert("template")
        nonAdditionalPropertyKeys.insert("namespace")
        nonAdditionalPropertyKeys.insert("language")
        nonAdditionalPropertyKeys.insert("params")
        nonAdditionalPropertyKeys.insert("referenceId")
        nonAdditionalPropertyKeys.insert("currency")
        nonAdditionalPropertyKeys.insert("paymentSettings")
        nonAdditionalPropertyKeys.insert("order")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

