//
// SetWhatsappBusinessEncryptionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SetWhatsappBusinessEncryptionRequest: Codable, JSONEncodable, Hashable {

    /** 2048-bit RSA public key in PEM format */
    public var businessPublicKey: String

    public init(businessPublicKey: String) {
        self.businessPublicKey = businessPublicKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case businessPublicKey = "business_public_key"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(businessPublicKey, forKey: .businessPublicKey)
    }
}

