//
// UpdateMeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateMeRequest: Codable, JSONEncodable, Hashable {

    /** Profile About section */
    public var about: String?
    public var address: String?
    /** Business description (max 256 characters) */
    public var description: String?
    public var email: String?
    /** Industry of the business */
    public var vertical: String?
    /** HTTPS URL or data:image/...;base64,... payload */
    public var photo: String?
    public var websites: [String]?

    public init(about: String? = nil, address: String? = nil, description: String? = nil, email: String? = nil, vertical: String? = nil, photo: String? = nil, websites: [String]? = nil) {
        self.about = about
        self.address = address
        self.description = description
        self.email = email
        self.vertical = vertical
        self.photo = photo
        self.websites = websites
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case about
        case address
        case description
        case email
        case vertical
        case photo
        case websites
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(about, forKey: .about)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(vertical, forKey: .vertical)
        try container.encodeIfPresent(photo, forKey: .photo)
        try container.encodeIfPresent(websites, forKey: .websites)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        about = try container.decodeIfPresent(String.self, forKey: .about)
        address = try container.decodeIfPresent(String.self, forKey: .address)
        description = try container.decodeIfPresent(String.self, forKey: .description)
        email = try container.decodeIfPresent(String.self, forKey: .email)
        vertical = try container.decodeIfPresent(String.self, forKey: .vertical)
        photo = try container.decodeIfPresent(String.self, forKey: .photo)
        websites = try container.decodeIfPresent([String].self, forKey: .websites)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("about")
        nonAdditionalPropertyKeys.insert("address")
        nonAdditionalPropertyKeys.insert("description")
        nonAdditionalPropertyKeys.insert("email")
        nonAdditionalPropertyKeys.insert("vertical")
        nonAdditionalPropertyKeys.insert("photo")
        nonAdditionalPropertyKeys.insert("websites")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

